#!/usr/bin/env node
// Saves Claude in-conversation scores to scored-clips.json
'use strict';
const fs = require('fs'), path = require('path');
const [,, runId] = process.argv;
const RUN_DIR = path.join('projects', runId);
const downloaded = JSON.parse(fs.readFileSync(path.join(RUN_DIR,'clips','downloaded-clips.json'),'utf8'));

// Raw scores from Claude scoring session
const RAW = [
  // Batch 1
  {id:'DreamyEnchantingWaffleKlappa-SGrWFTl171kLTDpU',retentionScore:62,funnyScore:55,payoffStrength:50,contextClarity:75,noveltyScore:50,shortsPotential:65,longFormPotential:40,transitionPotential:55,cooldownPotential:75,toxicityRisk:5,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:65,emotionalCategory:'emotional',reasoning:'CodeMiko reacts to a dog named after Ada Wong — cute and accessible but low on laughs and payoff'},
  {id:'GiantHomelyCarabeefPermaSmug-6of2pDOx0-oD0B6x',retentionScore:45,funnyScore:50,payoffStrength:45,contextClarity:35,noveltyScore:50,shortsPotential:40,longFormPotential:55,transitionPotential:40,cooldownPotential:45,toxicityRisk:20,singingScore:0,dancingScore:0,rageScore:15,thumbnailPotential:60,emotionalCategory:'surprise',reasoning:'xQc reaction clip with no transcript — impossible to assess without knowing what he\'s reacting to'},
  {id:'HeadstrongTangentialDragonFrankerZ-l7INf7EYU9U3dS-1',retentionScore:82,funnyScore:85,payoffStrength:80,contextClarity:88,noveltyScore:75,shortsPotential:88,longFormPotential:72,transitionPotential:60,cooldownPotential:25,toxicityRisk:5,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:70,emotionalCategory:'cringe',reasoning:'Street stranger gets "business email" instead of phone number — immediately funny, great payoff, works for any audience'},
  {id:'TubularEndearingFlyDuDudu-jB9HwWle4lrqNqgQ',retentionScore:55,funnyScore:45,payoffStrength:50,contextClarity:65,noveltyScore:40,shortsPotential:55,longFormPotential:40,transitionPotential:65,cooldownPotential:75,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:45,emotionalCategory:'other',reasoning:'Jinnytty recommends Romania with mild "but not with bike" punchline — too low-energy for compilation unless used as cooldown filler'},
  {id:'LightTrustworthyCodDoubleRainbow-_IAwf7Xkcv9OIwId',retentionScore:78,funnyScore:82,payoffStrength:75,contextClarity:72,noveltyScore:65,shortsPotential:72,longFormPotential:68,transitionPotential:45,cooldownPotential:30,toxicityRisk:30,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:65,emotionalCategory:'cringe',reasoning:'Accidental foot-job innuendo with perfect chat timing — funny cringe that works without knowing the streamer'},
  {id:'RacyFrozenDurianFUNgineer-BA7sjUdnNV_Y5Ofo',retentionScore:55,funnyScore:52,payoffStrength:60,contextClarity:42,noveltyScore:50,shortsPotential:48,longFormPotential:55,transitionPotential:50,cooldownPotential:40,toxicityRisk:5,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:35,emotionalCategory:'fail',reasoning:'Team kills themselves clearing mines — title tells the joke but requires Dota knowledge to fully appreciate'},
  {id:'IcySmilingNigiriKeyboardCat-8_HIg9BgIokEkarW',retentionScore:40,funnyScore:40,payoffStrength:35,contextClarity:30,noveltyScore:40,shortsPotential:45,longFormPotential:35,transitionPotential:40,cooldownPotential:50,toxicityRisk:10,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:50,emotionalCategory:'surprise',reasoning:'No audio transcript — cannot assess content quality beyond the generic IRL title "wowza"'},
  {id:'JoyousSavageMelonKevinTurtle-BRd8hQcA91EBSXK2',retentionScore:60,funnyScore:55,payoffStrength:65,contextClarity:55,noveltyScore:50,shortsPotential:65,longFormPotential:45,transitionPotential:55,cooldownPotential:35,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:40,emotionalCategory:'gameplay',reasoning:'PoE2 clip of repeating "our damage is good" while deleting content — exciting but gaming-niche payoff'},
  // Batch 2
  {id:'TentativeDiligentMageBloodTrail-6EABv8lfMtIMUH6J',retentionScore:35,funnyScore:20,payoffStrength:25,contextClarity:30,noveltyScore:30,shortsPotential:25,longFormPotential:45,transitionPotential:35,cooldownPotential:55,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:20,emotionalCategory:'gameplay',reasoning:'Build explanation clip with no exciting moment — educational PoE2 content that won\'t engage general viewers'},
  {id:'PeacefulGiantWalletFeelsBadMan-1V5ByWDxq0TOhUXA',retentionScore:45,funnyScore:55,payoffStrength:45,contextClarity:40,noveltyScore:55,shortsPotential:50,longFormPotential:42,transitionPotential:40,cooldownPotential:40,toxicityRisk:10,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:35,emotionalCategory:'gameplay',reasoning:'Funny clip title "DiarrheaBlast" but no transcript to confirm the content'},
  {id:'MagnificentHeartlessAyeayeStrawBeary-zo2njwFHJKL65_FS',retentionScore:72,funnyScore:75,payoffStrength:70,contextClarity:60,noveltyScore:65,shortsPotential:65,longFormPotential:68,transitionPotential:45,cooldownPotential:30,toxicityRisk:25,singingScore:0,dancingScore:0,rageScore:30,thumbnailPotential:55,emotionalCategory:'fail',reasoning:'Someone tells Quin69 to gamble everything if he loves unpredictability — funny escalating argument that works without PoE context'},
  {id:'AgitatedGlutenFreeOstrichAliens-h4Ftv89Rl9Vc3oYH',retentionScore:50,funnyScore:20,payoffStrength:30,contextClarity:45,noveltyScore:25,shortsPotential:55,longFormPotential:30,transitionPotential:40,cooldownPotential:65,toxicityRisk:20,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:65,emotionalCategory:'other',reasoning:'Pool streamer clip with no dialogue — likely visual content with no assessable hook'},
  {id:'TenderSincereWatermelonDxCat-0zYsEI5glhS_a7Dc',retentionScore:42,funnyScore:45,payoffStrength:38,contextClarity:35,noveltyScore:40,shortsPotential:40,longFormPotential:35,transitionPotential:40,cooldownPotential:45,toxicityRisk:10,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:40,emotionalCategory:'fail',reasoning:'DBD player getting distracted — unclear moment that requires context and doesn\'t deliver for general audiences'},
  {id:'ColdbloodedModernEggplantBudStar-Ho7fGBdZ-TKnfMJb',retentionScore:65,funnyScore:62,payoffStrength:68,contextClarity:65,noveltyScore:55,shortsPotential:70,longFormPotential:60,transitionPotential:50,cooldownPotential:40,toxicityRisk:5,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:70,emotionalCategory:'surprise',reasoning:'Miyoung gets genuinely jumpscared clutching a 1v1 — solid accessible reaction clip'},
  {id:'ScaryNiceChimpanzeeDxAbomb-YV0NP-dbk0oDO73O',retentionScore:52,funnyScore:55,payoffStrength:48,contextClarity:45,noveltyScore:50,shortsPotential:50,longFormPotential:45,transitionPotential:50,cooldownPotential:55,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:45,emotionalCategory:'fail',reasoning:'Confused 7DTD raid with "witchcraft" commentary — mildly funny but no clear payoff for non-fans'},
  {id:'AliveBoxyMilkBibleThump-piUi-Wbx8Y9TxQsX',retentionScore:58,funnyScore:15,payoffStrength:45,contextClarity:72,noveltyScore:55,shortsPotential:60,longFormPotential:45,transitionPotential:45,cooldownPotential:72,toxicityRisk:0,singingScore:85,dancingScore:0,rageScore:0,thumbnailPotential:50,emotionalCategory:'emotional',reasoning:'Sincere original comeback song — works only as emotional cooldown, not laugh material'},
  // Batch 3
  {id:'AmazingPoliteWoodpeckerFUNgineer-c2g8ZNq-_27VSSRm',retentionScore:35,funnyScore:30,payoffStrength:30,contextClarity:30,noveltyScore:30,shortsPotential:35,longFormPotential:20,transitionPotential:35,cooldownPotential:25,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:30,emotionalCategory:'other',reasoning:'9.6-second clip with no discernible moment — far too short and context-dependent'},
  {id:'ImpartialElegantShieldJKanStyle-ecAfzH7OF5-HhcWP',retentionScore:40,funnyScore:10,payoffStrength:30,contextClarity:50,noveltyScore:40,shortsPotential:45,longFormPotential:40,transitionPotential:40,cooldownPotential:65,toxicityRisk:0,singingScore:70,dancingScore:0,rageScore:0,thumbnailPotential:40,emotionalCategory:'other',reasoning:'Music clip with minimal speech — quality depends entirely on unheard music performance'},
  {id:'MoralGracefulZucchiniPermaSmug-2AHl1kI7DZeZdSko',retentionScore:52,funnyScore:55,payoffStrength:50,contextClarity:55,noveltyScore:55,shortsPotential:52,longFormPotential:48,transitionPotential:45,cooldownPotential:60,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:45,emotionalCategory:'surprise',reasoning:'Drum game generates a character named Lake from Frost+Flame parents — mildly amusing with limited general appeal'},
  {id:'ConsiderateTubularTortoiseTwitchRaid-GWCQ8-bCpKQi7NKb',retentionScore:75,funnyScore:58,payoffStrength:72,contextClarity:78,noveltyScore:60,shortsPotential:70,longFormPotential:65,transitionPotential:50,cooldownPotential:45,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:72,emotionalCategory:'emotional',reasoning:'Streamer gets hit with 1000 gifted subs and loses it — genuine shock universally understood on Twitch'},
  {id:'ResilientCrepuscularBeanTwitchRaid-eQFz5mRYs1KZc9MG',retentionScore:45,funnyScore:50,payoffStrength:45,contextClarity:45,noveltyScore:50,shortsPotential:48,longFormPotential:42,transitionPotential:45,cooldownPotential:40,toxicityRisk:5,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:35,emotionalCategory:'fail',reasoning:'GTA V clip with ironic title but no transcript to assess the visual moment'},
  {id:'SnappyCuriousFennelYee-18d9fagi578mowkX',retentionScore:50,funnyScore:40,payoffStrength:55,contextClarity:45,noveltyScore:45,shortsPotential:52,longFormPotential:48,transitionPotential:45,cooldownPotential:35,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:40,emotionalCategory:'gameplay',reasoning:'CS2 clip with no audio — can\'t assess the reaction quality, likely a mechanical play'},
  {id:'PowerfulFuriousPeachSoBayed-tiScHl5nR1NbNJRf',retentionScore:35,funnyScore:40,payoffStrength:35,contextClarity:25,noveltyScore:40,shortsPotential:35,longFormPotential:30,transitionPotential:35,cooldownPotential:40,toxicityRisk:10,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:35,emotionalCategory:'other',reasoning:'No transcript and non-English title makes this JC clip inaccessible for English audiences'},
  {id:'BlushingSillySardineDerp-JBZgz8gMu7LMaPOn',retentionScore:62,funnyScore:68,payoffStrength:58,contextClarity:72,noveltyScore:55,shortsPotential:70,longFormPotential:45,transitionPotential:55,cooldownPotential:35,toxicityRisk:15,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:55,emotionalCategory:'cringe',reasoning:'Streamer casually announces they\'re going to fart while Apex loads — short, immediately funny, no context needed'},
  // Batch 4
  {id:'DeterminedBlazingClintmullinsOMGScoots-ZRWR8PdRdGEYvQK4',retentionScore:60,funnyScore:65,payoffStrength:58,contextClarity:52,noveltyScore:60,shortsPotential:58,longFormPotential:55,transitionPotential:50,cooldownPotential:65,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:50,emotionalCategory:'cringe',reasoning:'D&D players arguing who\'s fairest while in-character — cute banter that might work but requires RP context'},
  {id:'StrangeKawaiiHippoNerfRedBlaster-qmZxLer3fBOZYoKF',retentionScore:60,funnyScore:65,payoffStrength:55,contextClarity:65,noveltyScore:60,shortsPotential:65,longFormPotential:48,transitionPotential:50,cooldownPotential:55,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:52,emotionalCategory:'cringe',reasoning:'Streamer says "I knahve to blow my knose" in a funny voice — charming small moment that works as palette cleanser'},
  {id:'WonderfulManlyGalagoKAPOW-6eAAgP0FAeYlx-BQ',retentionScore:62,funnyScore:65,payoffStrength:60,contextClarity:52,noveltyScore:58,shortsPotential:60,longFormPotential:55,transitionPotential:50,cooldownPotential:30,toxicityRisk:10,singingScore:0,dancingScore:0,rageScore:25,thumbnailPotential:50,emotionalCategory:'fail',reasoning:'Streamer panics while friend dies off-screen — chaotic energy works without game knowledge, title tells the joke'},
  {id:'FlaccidWanderingStinkbugKappaRoss-L7vNDhZ3h5ZkOqdm',retentionScore:45,funnyScore:48,payoffStrength:42,contextClarity:40,noveltyScore:45,shortsPotential:48,longFormPotential:42,transitionPotential:45,cooldownPotential:40,toxicityRisk:10,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:42,emotionalCategory:'other',reasoning:'No transcript for Jynxzi Minecraft clip — can\'t assess the specific viral moment'},
  {id:'SneakySpikyShrimpCoolStoryBro-KYxNThvsou1hxOZW',retentionScore:65,funnyScore:68,payoffStrength:62,contextClarity:62,noveltyScore:60,shortsPotential:68,longFormPotential:52,transitionPotential:52,cooldownPotential:30,toxicityRisk:20,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:65,emotionalCategory:'cringe',reasoning:'IRL confrontation with aggressive "not really mate, mate" — short, punchy, accessible street moment'},
  {id:'SmoothUnusualOkapiNononoCat-eQ3AxQq9o8_X1qfG',retentionScore:52,funnyScore:55,payoffStrength:50,contextClarity:48,noveltyScore:50,shortsPotential:52,longFormPotential:48,transitionPotential:48,cooldownPotential:40,toxicityRisk:5,singingScore:0,dancingScore:0,rageScore:10,thumbnailPotential:40,emotionalCategory:'fail',reasoning:'Gets 4 kills and still loses in Valorant — gaming frustration clip with poor audio quality from transcript'},
  {id:'HotObeseUdonFeelsBadMan-bLq_5HdOgcG-zDbm',retentionScore:70,funnyScore:78,payoffStrength:68,contextClarity:65,noveltyScore:68,shortsPotential:78,longFormPotential:45,transitionPotential:60,cooldownPotential:30,toxicityRisk:20,singingScore:0,dancingScore:0,rageScore:30,thumbnailPotential:60,emotionalCategory:'surprise',reasoning:'"Cats don\'t smoke!" — short, punchy, immediately funny and works without any context'},
  {id:'MiniatureHilariousUdonFeelsBadMan-ZoDok_x6qnSp6aXl',retentionScore:42,funnyScore:45,payoffStrength:40,contextClarity:38,noveltyScore:42,shortsPotential:45,longFormPotential:38,transitionPotential:40,cooldownPotential:40,toxicityRisk:5,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:35,emotionalCategory:'gameplay',reasoning:'Short Apex clip — "I need you to leave" line suggests a funny encounter but lacks visible payoff'},
  // Batch 5
  {id:'FamousSlipperyNuggetsLeeroyJenkins-31XB_hl4Tyv1qeMm',retentionScore:40,funnyScore:35,payoffStrength:40,contextClarity:35,noveltyScore:35,shortsPotential:40,longFormPotential:38,transitionPotential:38,cooldownPotential:35,toxicityRisk:5,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:40,emotionalCategory:'gameplay',reasoning:'Apex gameplay clip with no audio — can\'t assess the moment quality at all'},
  {id:'TastyPeacefulSlothUWot-CJ2PzFbYGlcBKQWh',retentionScore:45,funnyScore:40,payoffStrength:38,contextClarity:45,noveltyScore:35,shortsPotential:52,longFormPotential:35,transitionPotential:38,cooldownPotential:55,toxicityRisk:15,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:60,emotionalCategory:'other',reasoning:'Spanish pool streamer self-praising — visual appeal without language barrier but minimal comedic payoff'},
  {id:'BeautifulEnjoyableAmazonPogChamp-gBrh131ALJF10WbX',retentionScore:82,funnyScore:75,payoffStrength:80,contextClarity:80,noveltyScore:78,shortsPotential:82,longFormPotential:75,transitionPotential:55,cooldownPotential:25,toxicityRisk:5,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:78,emotionalCategory:'surprise',reasoning:'IRL streamer finds an actual grenade while detecting — universal panic + danger makes this immediately gripping'},
  {id:'ExuberantCleanLatteMrDestructoid-RkF399di4i15V3V1',retentionScore:48,funnyScore:50,payoffStrength:42,contextClarity:45,noveltyScore:45,shortsPotential:48,longFormPotential:48,transitionPotential:45,cooldownPotential:40,toxicityRisk:25,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:40,emotionalCategory:'other',reasoning:'Casual Minecraft Nether banter with a problematic Epstein Island reference'},
  {id:'LuckyHotRabbitDuDudu-Tb8qLnhWoblP6ZAN',retentionScore:38,funnyScore:30,payoffStrength:35,contextClarity:35,noveltyScore:35,shortsPotential:40,longFormPotential:35,transitionPotential:35,cooldownPotential:45,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:35,emotionalCategory:'other',reasoning:'Fitness clip with no transcript — workout content with no discernible viral moment'},
  {id:'HungryLazyOxBIRB-LD4-CK534rs23anX',retentionScore:68,funnyScore:72,payoffStrength:70,contextClarity:65,noveltyScore:65,shortsPotential:70,longFormPotential:62,transitionPotential:50,cooldownPotential:30,toxicityRisk:35,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:60,emotionalCategory:'cringe',reasoning:'IRL streamer jokes "I can spit on your tits" instead of signing autographs — crude shock moment with slight toxicity risk'},
  {id:'TacitLachrymoseAlligatorTooSpicy-TXnvWuLkymFccJPL',retentionScore:55,funnyScore:55,payoffStrength:52,contextClarity:45,noveltyScore:48,shortsPotential:58,longFormPotential:40,transitionPotential:45,cooldownPotential:38,toxicityRisk:10,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:48,emotionalCategory:'surprise',reasoning:'Spanish DBD jumpscare "what a scare! Fuck you!" — emotion is universal but Spanish dialog limits English audience appeal'},
  {id:'PowerfulKnottyGiraffeSwiftRage-FHBLH8jP_JzTV3lR',retentionScore:42,funnyScore:38,payoffStrength:38,contextClarity:40,noveltyScore:38,shortsPotential:40,longFormPotential:38,transitionPotential:38,cooldownPotential:45,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:38,emotionalCategory:'fail',reasoning:'German IRL van breakdown on a Friday — relatable frustration but too low-energy and requires German'},
  // Batch 6
  {id:'EphemeralDeafDragonflyWOOP-5dQm_oVpcixU0u0Y',retentionScore:68,funnyScore:78,payoffStrength:72,contextClarity:85,noveltyScore:72,shortsPotential:80,longFormPotential:55,transitionPotential:60,cooldownPotential:45,toxicityRisk:10,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:60,emotionalCategory:'surprise',reasoning:'"Coffee is bean soup — it\'s SOUP SEASON BITCH!" — instantly funny absurd logic, short and punchy'},
  {id:'SuperBovineMelonPraiseIt-_UTwYnghQaKkZldS',retentionScore:38,funnyScore:38,payoffStrength:35,contextClarity:35,noveltyScore:35,shortsPotential:38,longFormPotential:38,transitionPotential:38,cooldownPotential:40,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:30,emotionalCategory:'other',reasoning:'Generic Minecraft banter with no clear payoff — forgettable content'},
  {id:'TriumphantSneakyBoarJKanStyle-x9Cv0n1bXV77ic6f',retentionScore:38,funnyScore:30,payoffStrength:40,contextClarity:42,noveltyScore:38,shortsPotential:45,longFormPotential:30,transitionPotential:35,cooldownPotential:45,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:42,emotionalCategory:'other',reasoning:'11-second rope climb fitness clip with almost no audio — impressive physically but no comedy hook'},
  {id:'AgitatedEphemeralSpiderGingerPower-q2pQdF43rsftaKfS',retentionScore:35,funnyScore:35,payoffStrength:32,contextClarity:25,noveltyScore:30,shortsPotential:35,longFormPotential:28,transitionPotential:30,cooldownPotential:30,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:25,emotionalCategory:'fail',reasoning:'German Minecraft clip — completely inaccessible for English audience without German or game context'},
  {id:'OriginalCleanGnatTwitchRPG-W-6EE--ChZJzPuju',retentionScore:42,funnyScore:18,payoffStrength:25,contextClarity:45,noveltyScore:25,shortsPotential:50,longFormPotential:28,transitionPotential:30,cooldownPotential:55,toxicityRisk:20,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:62,emotionalCategory:'other',reasoning:'Pool streamer checking outfit — purely visual content with no comedic or emotional hook'},
  {id:'TransparentCaringLemurOneHand-QVFMp7AAjsz_oEwm',retentionScore:62,funnyScore:60,payoffStrength:58,contextClarity:72,noveltyScore:58,shortsPotential:68,longFormPotential:55,transitionPotential:48,cooldownPotential:35,toxicityRisk:15,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:55,emotionalCategory:'other',reasoning:'Fitness streamer delivers blunt "go to therapy and have a salad" reality check — energetic and accessible without context'},
  {id:'FilthyManlySoybeanRalpherZ-zXasseekQf1RBtOm',retentionScore:38,funnyScore:30,payoffStrength:35,contextClarity:35,noveltyScore:35,shortsPotential:40,longFormPotential:35,transitionPotential:35,cooldownPotential:45,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:35,emotionalCategory:'other',reasoning:'Fitness clip with no transcript — duplicate in dataset, no discernible viral moment'},
  {id:'FragileRamshackleGuanacoSoonerLater-wFwouufWceuPppoH',retentionScore:35,funnyScore:28,payoffStrength:25,contextClarity:38,noveltyScore:28,shortsPotential:40,longFormPotential:25,transitionPotential:28,cooldownPotential:48,toxicityRisk:15,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:55,emotionalCategory:'other',reasoning:'Pool streamer doing channel points with no discernible hook'},
  // Batch 7
  {id:'SmoggyRealCatBrokeBack-LKSO6q1zIz-dXqQ4',retentionScore:45,funnyScore:48,payoffStrength:42,contextClarity:42,noveltyScore:40,shortsPotential:45,longFormPotential:42,transitionPotential:42,cooldownPotential:35,toxicityRisk:15,singingScore:0,dancingScore:0,rageScore:15,thumbnailPotential:40,emotionalCategory:'fail',reasoning:'Jynxzi frustrated in Minecraft — standard gaming frustration without a clear payoff'},
  {id:'RamshackleBlatantSandstormHeyGirl-A2fNxYZ4I-zE0m3Q',retentionScore:58,funnyScore:60,payoffStrength:55,contextClarity:55,noveltyScore:55,shortsPotential:60,longFormPotential:52,transitionPotential:48,cooldownPotential:50,toxicityRisk:0,singingScore:75,dancingScore:0,rageScore:0,thumbnailPotential:52,emotionalCategory:'cringe',reasoning:'Spanish podcast hosts singing Britney badly — charming cringe, accessible since everyone knows Baby One More Time'},
  {id:'CrunchyResilientBeanPrimeMe-oI7K82ihC7Vayn3x',retentionScore:45,funnyScore:48,payoffStrength:45,contextClarity:42,noveltyScore:42,shortsPotential:45,longFormPotential:45,transitionPotential:42,cooldownPotential:38,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:35,emotionalCategory:'fail',reasoning:'Minecraft clip titled "Ron Died" — death moment not captured in transcript'},
  {id:'PlainSmilingStorkPogChamp-2bx0Otjq25IxVyiy',retentionScore:20,funnyScore:5,payoffStrength:10,contextClarity:25,noveltyScore:15,shortsPotential:15,longFormPotential:20,transitionPotential:15,cooldownPotential:20,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:10,emotionalCategory:'gameplay',reasoning:'Portuguese PoE2 tutorial clip — zero entertainment value for a compilation audience'},
  {id:'GorgeousWonderfulWheelShadyLulu-xLilIOvN4M9h5yQO',retentionScore:30,funnyScore:25,payoffStrength:25,contextClarity:35,noveltyScore:25,shortsPotential:15,longFormPotential:20,transitionPotential:15,cooldownPotential:10,toxicityRisk:85,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:15,emotionalCategory:'cringe',reasoning:'Podcast discussing scat using a slur — severely toxic content, must be excluded'},
  {id:'PeacefulSillyTeaPogChamp-3dqf4_VPkQIvEQ4v',retentionScore:42,funnyScore:45,payoffStrength:38,contextClarity:30,noveltyScore:38,shortsPotential:40,longFormPotential:38,transitionPotential:38,cooldownPotential:40,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:32,emotionalCategory:'gameplay',reasoning:'German DBD gameplay fully inaccessible without both German and DBD knowledge'},
  {id:'DependableSparklyGoatCoolStoryBob-MVzYMJxf9qfDepQg',retentionScore:38,funnyScore:40,payoffStrength:35,contextClarity:32,noveltyScore:35,shortsPotential:38,longFormPotential:30,transitionPotential:32,cooldownPotential:35,toxicityRisk:5,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:30,emotionalCategory:'fail',reasoning:'Short DBD refusal clip — impossible to assess without visual context'},
  {id:'ChillyScrumptiousJalapenoRlyTho-MoSkwPz-T2yL44TT',retentionScore:62,funnyScore:68,payoffStrength:60,contextClarity:65,noveltyScore:68,shortsPotential:65,longFormPotential:55,transitionPotential:52,cooldownPotential:48,toxicityRisk:5,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:52,emotionalCategory:'other',reasoning:'"What if Garfield did lasagna ASMR" — bizarre but charming brain dump that lands without context'},
  // Batch 8
  {id:'ArborealPlayfulPeafowlSwiftRage-fnVwfe5P_O-nhceR',retentionScore:55,funnyScore:40,payoffStrength:48,contextClarity:55,noveltyScore:55,shortsPotential:58,longFormPotential:50,transitionPotential:45,cooldownPotential:45,toxicityRisk:35,singingScore:75,dancingScore:0,rageScore:0,thumbnailPotential:50,emotionalCategory:'other',reasoning:'Live rap performance with explicit lyrics — unique concept but content limits usability in a general compilation'},
  {id:'SplendidAliveDugongSuperVinlin-kJRQHLqqxE1xjaSf',retentionScore:82,funnyScore:90,payoffStrength:85,contextClarity:80,noveltyScore:80,shortsPotential:88,longFormPotential:72,transitionPotential:62,cooldownPotential:25,toxicityRisk:15,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:72,emotionalCategory:'cringe',reasoning:'Spanish cooking streamer opens with "it\'s good it didn\'t come out with poop" — universally hilarious, no language barrier for this kind of humor'},
  {id:'SmoggyBlightedSharkStrawBeary-a9S2-xJU0PK9Ozp_',retentionScore:40,funnyScore:32,payoffStrength:38,contextClarity:42,noveltyScore:32,shortsPotential:42,longFormPotential:35,transitionPotential:35,cooldownPotential:45,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:45,emotionalCategory:'gameplay',reasoning:'Weightlifting clip — impressive physically but no comedic or emotional hook beyond the lift itself'},
  {id:'NeighborlyFuriousArugulaThisIsSparta-faRhd_5Ht3JJfhDa',retentionScore:70,funnyScore:82,payoffStrength:80,contextClarity:82,noveltyScore:70,shortsPotential:80,longFormPotential:40,transitionPotential:65,cooldownPotential:30,toxicityRisk:15,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:55,emotionalCategory:'cringe',reasoning:'6-second accidental innuendo "come take out my thing if you want" — perfectly punchy without any context'},
  {id:'WildCrunchyWallabyResidentSleeper-JvXKzzZqvvYwCRFm',retentionScore:50,funnyScore:55,payoffStrength:50,contextClarity:58,noveltyScore:50,shortsPotential:55,longFormPotential:35,transitionPotential:40,cooldownPotential:20,toxicityRisk:75,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:42,emotionalCategory:'cringe',reasoning:'Streamer explicitly yells sexual phrases then self-clips it — too explicit for general compilation'},
  {id:'WildTriumphantSkunkTBCheesePull-l-XSEXqUPofj9oVC',retentionScore:35,funnyScore:38,payoffStrength:32,contextClarity:28,noveltyScore:32,shortsPotential:35,longFormPotential:28,transitionPotential:30,cooldownPotential:32,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:28,emotionalCategory:'other',reasoning:'Repetitive "I got it" loop without visual context — likely a humorous moment we can\'t evaluate from audio alone'},
  {id:'UnusualLitigiousFishAsianGlow-nEyqbdskoykOXuhP',retentionScore:40,funnyScore:38,payoffStrength:38,contextClarity:35,noveltyScore:35,shortsPotential:40,longFormPotential:38,transitionPotential:35,cooldownPotential:35,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:35,emotionalCategory:'gameplay',reasoning:'Valorant clip with garbled transcript — likely a highlight but audio quality makes it unassessable'},
  {id:'AgitatedSourDiscOSfrog-FGaXDAvjLtZgJtQR',retentionScore:58,funnyScore:62,payoffStrength:55,contextClarity:52,noveltyScore:55,shortsPotential:60,longFormPotential:50,transitionPotential:48,cooldownPotential:42,toxicityRisk:5,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:52,emotionalCategory:'fail',reasoning:'German IRL complains about being overtaken while on a green light — mildly ironic self-own but requires German'},
  // Batch 9
  {id:'SweetPatientDonutSeemsGood-2X14xoxGM8VrYpLO',retentionScore:40,funnyScore:45,payoffStrength:40,contextClarity:38,noveltyScore:40,shortsPotential:42,longFormPotential:25,transitionPotential:38,cooldownPotential:32,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:35,emotionalCategory:'surprise',reasoning:'6-second German IRL clip — too short and requires German to understand'},
  {id:'AlertTemperedPotGrammarKing-_RTcTyCfbXgdGDEh',retentionScore:35,funnyScore:22,payoffStrength:25,contextClarity:40,noveltyScore:22,shortsPotential:40,longFormPotential:25,transitionPotential:28,cooldownPotential:52,toxicityRisk:20,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:58,emotionalCategory:'other',reasoning:'Pool streamer talking about post-stream cleanup — purely background content with no moment worth including'},
  {id:'GoldenCalmTermitePRChase-ZVX5d5BbbFaaEw2i',retentionScore:30,funnyScore:25,payoffStrength:22,contextClarity:35,noveltyScore:28,shortsPotential:30,longFormPotential:22,transitionPotential:25,cooldownPotential:55,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:28,emotionalCategory:'other',reasoning:'Sleep streamer clip with no audio — extremely dry visual gag with no audio component'},
  {id:'StrangeScarySquidPartyTime-3Zgz75b7ErEsnbd0',retentionScore:72,funnyScore:75,payoffStrength:70,contextClarity:72,noveltyScore:68,shortsPotential:75,longFormPotential:62,transitionPotential:55,cooldownPotential:30,toxicityRisk:20,singingScore:0,dancingScore:0,rageScore:40,thumbnailPotential:65,emotionalCategory:'rage',reasoning:'Streamer loses it after nobody bought anything from their kitchen menu all stream — relatable frustrated energy'},
  {id:'RudeBreakableSalmonNononoCat-gAMF-8FBJCOmoNfu',retentionScore:68,funnyScore:72,payoffStrength:68,contextClarity:75,noveltyScore:65,shortsPotential:78,longFormPotential:45,transitionPotential:60,cooldownPotential:40,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:68,emotionalCategory:'surprise',reasoning:'Person gets smacked by a cat and is genuinely confused — 13-second clip, immediately funny, needs zero context'},
  {id:'VibrantSmokyHyenaPlanking-TIfmmMWZbRlBB0bu',retentionScore:60,funnyScore:62,payoffStrength:58,contextClarity:58,noveltyScore:55,shortsPotential:65,longFormPotential:45,transitionPotential:52,cooldownPotential:38,toxicityRisk:5,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:55,emotionalCategory:'surprise',reasoning:'"Give me the powder!" German IRL jumpscare — the panic transcends language, short and punchy'},
  {id:'ConcernedLazyPresidentDatSheffy-tE-YA7m5ni6GlWtY',retentionScore:48,funnyScore:52,payoffStrength:45,contextClarity:42,noveltyScore:48,shortsPotential:48,longFormPotential:45,transitionPotential:42,cooldownPotential:50,toxicityRisk:15,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:38,emotionalCategory:'cringe',reasoning:'Jynxzi sleep stream banning the word "cuddle" from chat — specific to his community and hard to follow without context'},
  {id:'DarlingCooperativePistachioWoofer-wdz-dxgCN8LJCM2V',retentionScore:75,funnyScore:82,payoffStrength:78,contextClarity:78,noveltyScore:72,shortsPotential:78,longFormPotential:68,transitionPotential:55,cooldownPotential:40,toxicityRisk:20,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:65,emotionalCategory:'cringe',reasoning:'Jynxzi sets hilarious bed-sharing rules including "no bed humping" — immediately funny, no context needed'},
  // Batch 10
  {id:'SullenCalmVulturePJSugar-iB6Wz4xt2_aofkSg',retentionScore:48,funnyScore:50,payoffStrength:45,contextClarity:42,noveltyScore:45,shortsPotential:48,longFormPotential:45,transitionPotential:42,cooldownPotential:38,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:38,emotionalCategory:'other',reasoning:'Minecraft coordinate screenshot moment — inside joke for Jynxzi\'s audience that lacks compilation punch'},
  {id:'CourteousProtectivePeanutFreakinStinkin-sPwEFMEh71DmT94_',retentionScore:42,funnyScore:45,payoffStrength:42,contextClarity:38,noveltyScore:38,shortsPotential:42,longFormPotential:40,transitionPotential:38,cooldownPotential:32,toxicityRisk:30,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:32,emotionalCategory:'fail',reasoning:'Minecraft base gets destroyed with Epstein Island reference — toxicity risk and lacking payoff for general audiences'},
  {id:'WonderfulPlumpLionNotATK-OpgMCK85c4rkdwv6',retentionScore:38,funnyScore:30,payoffStrength:38,contextClarity:32,noveltyScore:32,shortsPotential:38,longFormPotential:35,transitionPotential:32,cooldownPotential:35,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:28,emotionalCategory:'gameplay',reasoning:'PoE2 boss fight clip — niche content with no visible reaction to hook general viewers'},
  {id:'OriginalMoldyCougarANELE-A8V4CIHorETdtxDj',retentionScore:48,funnyScore:50,payoffStrength:45,contextClarity:52,noveltyScore:45,shortsPotential:52,longFormPotential:42,transitionPotential:42,cooldownPotential:42,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:45,emotionalCategory:'fail',reasoning:'Polish streamer giving up on workout set — universal relatable moment, mildly funny but no big payoff'},
  {id:'NaiveCleanArugulaArsonNoSexy-x8sS2uYpiOaM9GKn',retentionScore:72,funnyScore:78,payoffStrength:72,contextClarity:80,noveltyScore:72,shortsPotential:80,longFormPotential:55,transitionPotential:62,cooldownPotential:35,toxicityRisk:5,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:58,emotionalCategory:'surprise',reasoning:'"We have cat shit coffee at home" — funny short clip playing on a recognizable meme format'},
  {id:'SmoggySmellyOilDansGame-_xU3y7Tuxlv8li7w',retentionScore:50,funnyScore:52,payoffStrength:50,contextClarity:42,noveltyScore:45,shortsPotential:50,longFormPotential:48,transitionPotential:42,cooldownPotential:35,toxicityRisk:30,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:38,emotionalCategory:'fail',reasoning:'Ron traps Jynxzi with another Epstein Island reference — moderate toxicity and requires knowing the duo'},
  {id:'BreakableTolerantGnatDerp-PnfVw6mC31l9bmIg',retentionScore:40,funnyScore:22,payoffStrength:25,contextClarity:38,noveltyScore:22,shortsPotential:45,longFormPotential:22,transitionPotential:28,cooldownPotential:52,toxicityRisk:20,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:55,emotionalCategory:'other',reasoning:'Spanish pool clip with no transcript — purely visual content with no hook'},
  {id:'CoweringExquisiteMacaroniBatChest-6GwODthqkcigYlUi',retentionScore:40,funnyScore:25,payoffStrength:25,contextClarity:42,noveltyScore:25,shortsPotential:48,longFormPotential:22,transitionPotential:28,cooldownPotential:50,toxicityRisk:20,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:58,emotionalCategory:'other',reasoning:'Spanish pool streamer admiring herself — visual content with minimal comedic value'},
  // Batch 11
  {id:'TsundereBelovedWhaleDAESuppy-ntaC3IS3faJYD8TK',retentionScore:48,funnyScore:42,payoffStrength:48,contextClarity:45,noveltyScore:40,shortsPotential:50,longFormPotential:40,transitionPotential:42,cooldownPotential:35,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:35,emotionalCategory:'gameplay',reasoning:'Second captainlance9 PoE2 damage test clip — virtually identical premise to another clip, redundant gaming content'},
  {id:'AggressiveKawaiiChimpanzeePeanutButterJellyTime-ZJsbPseKKckK7ods',retentionScore:35,funnyScore:28,payoffStrength:28,contextClarity:32,noveltyScore:28,shortsPotential:35,longFormPotential:28,transitionPotential:28,cooldownPotential:40,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:32,emotionalCategory:'other',reasoning:'Spanish cooking stream — no clip-worthy moment, generic recipe instruction'},
  {id:'ImpartialTrappedWallabyMoreCowbell-6Psu4Ex_AARdQSgt',retentionScore:42,funnyScore:38,payoffStrength:38,contextClarity:38,noveltyScore:32,shortsPotential:45,longFormPotential:30,transitionPotential:32,cooldownPotential:48,toxicityRisk:20,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:55,emotionalCategory:'surprise',reasoning:'Spanish pool streamer freaking out — three shainny_ clips already in dataset, language barrier limits appeal'},
  {id:'BadAbrasiveLemurDerp-r8Ce7GR2T-rpIeQ1',retentionScore:42,funnyScore:45,payoffStrength:40,contextClarity:38,noveltyScore:38,shortsPotential:42,longFormPotential:40,transitionPotential:38,cooldownPotential:35,toxicityRisk:10,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:38,emotionalCategory:'other',reasoning:'Fourth Jynxzi Minecraft clip with no transcript — nothing distinguishing it from others'},
  {id:'CulturedVainWoodpeckerNomNom-RUVQP_YpBPskvT28',retentionScore:50,funnyScore:55,payoffStrength:45,contextClarity:50,noveltyScore:52,shortsPotential:55,longFormPotential:42,transitionPotential:45,cooldownPotential:42,toxicityRisk:5,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:40,emotionalCategory:'cringe',reasoning:'CS2 player using voice chat to practice real-world small talk — unique premise but execution cuts off before payoff'},
  {id:'InventivePlayfulRabbitChefFrank-jl3kcUoIqGFmu1Pr',retentionScore:30,funnyScore:25,payoffStrength:25,contextClarity:25,noveltyScore:25,shortsPotential:28,longFormPotential:25,transitionPotential:25,cooldownPotential:30,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:22,emotionalCategory:'other',reasoning:'Spanish podcast clip with no audio — entirely inaccessible for English audience'},
  {id:'HedonisticIcyJaguarCorgiDerp-vMg8B7Km27wzMYBS',retentionScore:30,funnyScore:28,payoffStrength:28,contextClarity:25,noveltyScore:28,shortsPotential:30,longFormPotential:25,transitionPotential:25,cooldownPotential:28,toxicityRisk:5,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:25,emotionalCategory:'gameplay',reasoning:'Spanish CS2 clip with no transcript — completely inaccessible for English audience'},
  {id:'FaintSweetTermiteBabyRage-br2IjRHRO9AZwobG',retentionScore:35,funnyScore:35,payoffStrength:30,contextClarity:35,noveltyScore:30,shortsPotential:40,longFormPotential:28,transitionPotential:28,cooldownPotential:40,toxicityRisk:20,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:45,emotionalCategory:'other',reasoning:'Polish fitness clip with no transcript — language barrier makes this inaccessible'},
  // Batch 12
  {id:'LuckyDaintyGarlicBrokeBack-m4-jszwrwMsOcU1r',retentionScore:42,funnyScore:45,payoffStrength:40,contextClarity:38,noveltyScore:38,shortsPotential:42,longFormPotential:38,transitionPotential:38,cooldownPotential:38,toxicityRisk:10,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:32,emotionalCategory:'surprise',reasoning:'Gaming confusion clip with no clear payoff visible from transcript'},
  {id:'GrossPopularAnacondaDatBoi-lpu5h8THg6pwvvg3',retentionScore:38,funnyScore:22,payoffStrength:28,contextClarity:38,noveltyScore:32,shortsPotential:35,longFormPotential:30,transitionPotential:30,cooldownPotential:50,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:28,emotionalCategory:'emotional',reasoning:'Art appreciation in a music stream — wholesome but no clip-worthy moment for a compilation'},
  {id:'RelievedPhilanthropicMangoItsBoshyTime-rTjYQhDUnZHjweaB',retentionScore:68,funnyScore:72,payoffStrength:68,contextClarity:72,noveltyScore:62,shortsPotential:72,longFormPotential:52,transitionPotential:58,cooldownPotential:35,toxicityRisk:10,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:68,emotionalCategory:'surprise',reasoning:'Spanish Minecraft player gets jumpscared mid-commentary — the screaming lands universally regardless of language'},
  {id:'TawdryResoluteOcelotKappaClaus-6F-6E5W8eQtga6oa',retentionScore:68,funnyScore:68,payoffStrength:65,contextClarity:72,noveltyScore:62,shortsPotential:68,longFormPotential:62,transitionPotential:52,cooldownPotential:45,toxicityRisk:5,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:62,emotionalCategory:'cringe',reasoning:'Jinnytty teases chat about Romanian girl almost kissing her on the lips — charming IRL travel moment'},
  {id:'TenuousAstuteTurnipDxCat-WBmxMQSaCoFgfq-L',retentionScore:75,funnyScore:78,payoffStrength:72,contextClarity:88,noveltyScore:72,shortsPotential:82,longFormPotential:65,transitionPotential:58,cooldownPotential:42,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:60,emotionalCategory:'cringe',reasoning:'"There is no list" — profoundly relatable confession that lands for any viewer without any context'},
  {id:'AverageCheerfulAniseStrawBeary-VmFUYVK4eybi2ab8',retentionScore:72,funnyScore:75,payoffStrength:70,contextClarity:68,noveltyScore:68,shortsPotential:72,longFormPotential:62,transitionPotential:52,cooldownPotential:25,toxicityRisk:20,singingScore:0,dancingScore:0,rageScore:45,thumbnailPotential:65,emotionalCategory:'cringe',reasoning:'"You are the Phantom Menace in my life" — great specific insult that lands without needing context'},
  {id:'AcceptableSaltyOkapiAMPTropPunch-aX-CWwy3X1c48L2F',retentionScore:45,funnyScore:42,payoffStrength:38,contextClarity:48,noveltyScore:40,shortsPotential:45,longFormPotential:30,transitionPotential:35,cooldownPotential:45,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:35,emotionalCategory:'other',reasoning:'Brief mention of a great cameraman — too short and context-dependent without knowing who Arthur is'},
  {id:'SneakyPowerfulDaikonTriHard-PUDSWh9RCafyXVHj',retentionScore:45,funnyScore:42,payoffStrength:40,contextClarity:35,noveltyScore:45,shortsPotential:40,longFormPotential:42,transitionPotential:38,cooldownPotential:48,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:30,emotionalCategory:'other',reasoning:'Italian researcher passionately explains science — charming but Italian language limits English audience'},
  // Batch 13
  {id:'HorribleAntediluvianManateeArsonNoSexy-IB22usZMLDDbeBzA',retentionScore:65,funnyScore:55,payoffStrength:60,contextClarity:62,noveltyScore:68,shortsPotential:68,longFormPotential:55,transitionPotential:48,cooldownPotential:45,toxicityRisk:5,singingScore:45,dancingScore:0,rageScore:0,thumbnailPotential:52,emotionalCategory:'other',reasoning:'ARIatHOME freestyling a rap — second clip from same IRL, lacks immediate punch of the BUSINESS EMAIL one'},
  {id:'OilyDaintyLarkBloodTrail-0cnDu_I0aCk6jnAv',retentionScore:48,funnyScore:52,payoffStrength:48,contextClarity:42,noveltyScore:45,shortsPotential:50,longFormPotential:42,transitionPotential:42,cooldownPotential:42,toxicityRisk:5,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:42,emotionalCategory:'surprise',reasoning:'German streamer reacting with repeated "what will you do?" — needs visual context and German language'},
  {id:'YawningSavageHerdTheThing-ENVdt9CSONtmzPht',retentionScore:60,funnyScore:65,payoffStrength:58,contextClarity:65,noveltyScore:58,shortsPotential:62,longFormPotential:55,transitionPotential:48,cooldownPotential:45,toxicityRisk:10,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:52,emotionalCategory:'cringe',reasoning:'Jinnytty sets up a movie striptease music scenario then cuts off — charming cheeky tease'},
  {id:'TardySassySageOpieOP-PZnTcHCLgfKGZcl2',retentionScore:35,funnyScore:28,payoffStrength:28,contextClarity:30,noveltyScore:28,shortsPotential:30,longFormPotential:28,transitionPotential:28,cooldownPotential:38,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:25,emotionalCategory:'other',reasoning:'German IRL car repair mechanics in German — pure logistics with no comedy for English viewers'},
  {id:'ZealousLittlePandaSoBayed-aMAI8D1y28gZy3n_',retentionScore:45,funnyScore:45,payoffStrength:40,contextClarity:42,noveltyScore:40,shortsPotential:45,longFormPotential:38,transitionPotential:40,cooldownPotential:45,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:42,emotionalCategory:'cringe',reasoning:'Spanish IRL asking for Instagram — brief street interaction without a clear payoff for English audiences'},
  {id:'BenevolentRealCheesecakeDatSheffy-bZzpSBBPKzdrZC4e',retentionScore:55,funnyScore:55,payoffStrength:52,contextClarity:60,noveltyScore:52,shortsPotential:58,longFormPotential:50,transitionPotential:45,cooldownPotential:55,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:55,emotionalCategory:'emotional',reasoning:'Streamer reveals plushie while accidentally looking like she\'s choking it — cute moment that works without context'},
  {id:'DeliciousArborealRuffSmoocherZ-KVpokOK9rDZRaQky',retentionScore:30,funnyScore:25,payoffStrength:25,contextClarity:25,noveltyScore:25,shortsPotential:30,longFormPotential:25,transitionPotential:25,cooldownPotential:32,toxicityRisk:5,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:25,emotionalCategory:'other',reasoning:'Spanish JC clip with no audio — completely inaccessible for English compilation'},
  {id:'TastyPowerfulHippoEagleEye-qDrfILZrKduHG1rP',retentionScore:38,funnyScore:40,payoffStrength:35,contextClarity:32,noveltyScore:35,shortsPotential:40,longFormPotential:30,transitionPotential:32,cooldownPotential:38,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:35,emotionalCategory:'fail',reasoning:'German IRL with low speech density — without visual context the "aura loss" moment is unreadable'},
  // Batch 14
  {id:'RamshackleSolidMeerkatResidentSleeper-iu4xfjyNAEegHQGv',retentionScore:42,funnyScore:38,payoffStrength:38,contextClarity:42,noveltyScore:40,shortsPotential:40,longFormPotential:38,transitionPotential:38,cooldownPotential:45,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:35,emotionalCategory:'other',reasoning:'German IRL van life following off-road community — lacks a specific funny moment for a compilation'},
  {id:'SavoryCorrectDelicataNotLikeThis-uKqufVXgqQwZ1d49',retentionScore:30,funnyScore:25,payoffStrength:25,contextClarity:28,noveltyScore:28,shortsPotential:30,longFormPotential:25,transitionPotential:25,cooldownPotential:38,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:25,emotionalCategory:'other',reasoning:'Spanish IRL travel logistics — purely informational without comedic or emotional hook'},
  {id:'WonderfulRelatedShallotBudBlast-LPNI6FHYsVVHE80K',retentionScore:38,funnyScore:35,payoffStrength:32,contextClarity:32,noveltyScore:32,shortsPotential:38,longFormPotential:28,transitionPotential:30,cooldownPotential:35,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:28,emotionalCategory:'other',reasoning:'Very short German IRL clip — incomplete thought without enough context to assess'},
  {id:'BeautifulTrappedEndiveNinjaGrumpy-nd5p5USP21QUaYU4',retentionScore:28,funnyScore:28,payoffStrength:25,contextClarity:22,noveltyScore:25,shortsPotential:28,longFormPotential:22,transitionPotential:22,cooldownPotential:28,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:22,emotionalCategory:'other',reasoning:'Spanish JC clip with almost no dialogue — essentially unassessable'},
  {id:'SourPricklyCoyoteBlargNaut-O1Y_CeZewXucarEX',retentionScore:55,funnyScore:58,payoffStrength:52,contextClarity:48,noveltyScore:48,shortsPotential:55,longFormPotential:48,transitionPotential:48,cooldownPotential:40,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:48,emotionalCategory:'cringe',reasoning:'Two streamers hyping each other for a challenge — excited energy but Hungarian limits accessibility'},
  {id:'HonestHelplessSquidChefFrank-gaM8km_npb1RFs9A',retentionScore:42,funnyScore:40,payoffStrength:38,contextClarity:50,noveltyScore:38,shortsPotential:45,longFormPotential:30,transitionPotential:35,cooldownPotential:55,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:45,emotionalCategory:'emotional',reasoning:'IRL streamer tempting dog with cheese — cute but too short and in Spanish for compilation impact'},
  {id:'DepressedTentativeFlamingoPeteZaroll-dj6WpDpfAKxkiYW0',retentionScore:60,funnyScore:68,payoffStrength:65,contextClarity:62,noveltyScore:60,shortsPotential:68,longFormPotential:35,transitionPotential:60,cooldownPotential:40,toxicityRisk:5,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:55,emotionalCategory:'surprise',reasoning:'7-second "Wait, that is not ExtraEmily, bae" — punchy reveal moment that works as a quick laugh'},
  {id:'InquisitivePiliableAlmondWutFace-EsyTbEy4gknc8w5O',retentionScore:52,funnyScore:55,payoffStrength:50,contextClarity:48,noveltyScore:50,shortsPotential:55,longFormPotential:42,transitionPotential:48,cooldownPotential:40,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:45,emotionalCategory:'fail',reasoning:'German IRL "Glurak himself" fire clip — surprise fire element might be funny but requires German'},
  // Batch 15
  {id:'ResilientClumsyOctopusTheTarFu--uKDiz_lDLIgqrQN',retentionScore:48,funnyScore:42,payoffStrength:42,contextClarity:45,noveltyScore:45,shortsPotential:45,longFormPotential:42,transitionPotential:38,cooldownPotential:52,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:35,emotionalCategory:'emotional',reasoning:'German streamer recounting serious illness with friend watching so they wouldn\'t die — emotional but lacks funny payoff'},
  {id:'IntelligentInterestingAmazonWoofer-mT5BVpO01_NlTWAr',retentionScore:52,funnyScore:55,payoffStrength:50,contextClarity:52,noveltyScore:50,shortsPotential:55,longFormPotential:45,transitionPotential:45,cooldownPotential:42,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:48,emotionalCategory:'fail',reasoning:'German IRL on playground equipment struggling — mildly funny physical fail but requires German and visual context'},
  {id:'ArtisticElatedLocustTwitchRaid-3rQpJMp1OfF12tDQ',retentionScore:70,funnyScore:68,payoffStrength:72,contextClarity:72,noveltyScore:68,shortsPotential:75,longFormPotential:52,transitionPotential:55,cooldownPotential:42,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:62,emotionalCategory:'emotional',reasoning:'"He\'s in Spain. Since yesterday." — perfectly timed breakup bomb that lands without any Spanish knowledge'},
  {id:'PopularBluePanOneHand-W7QwG5Vo-GipoNN2',retentionScore:72,funnyScore:75,payoffStrength:70,contextClarity:70,noveltyScore:65,shortsPotential:72,longFormPotential:60,transitionPotential:52,cooldownPotential:25,toxicityRisk:25,singingScore:0,dancingScore:0,rageScore:60,thumbnailPotential:65,emotionalCategory:'rage',reasoning:'Jinnytty explodes on e-bike about content farming — "shut the fuck up you dumbass" lands perfectly without context'},
  {id:'KitschyLuckyLlamaBCWarrior-bh1IGOPKjjR71DHG',retentionScore:30,funnyScore:25,payoffStrength:25,contextClarity:25,noveltyScore:25,shortsPotential:20,longFormPotential:20,transitionPotential:20,cooldownPotential:15,toxicityRisk:90,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:20,emotionalCategory:'other',reasoning:'Clip uses racial slurs multiple times — must be excluded from any compilation regardless of other qualities'},
  {id:'PhilanthropicOilyPterodactylRitzMitz-cN2J_b2DHPr8Zg8y',retentionScore:35,funnyScore:32,payoffStrength:30,contextClarity:38,noveltyScore:30,shortsPotential:38,longFormPotential:25,transitionPotential:30,cooldownPotential:45,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:35,emotionalCategory:'other',reasoning:'Very short generic JC clip — "strong girl" moment too vague to assess without visuals'},
  {id:'SuccessfulMoistSharkRalpherZ-l-rcMreMcwG1wVAB',retentionScore:45,funnyScore:48,payoffStrength:42,contextClarity:48,noveltyScore:42,shortsPotential:48,longFormPotential:38,transitionPotential:38,cooldownPotential:45,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:38,emotionalCategory:'other',reasoning:'Spanish food combination discussion — mild food disgust humor without enough visual reaction to land'},
  {id:'JoyousEasyHerringCoolCat-pFvxyTfilp4HRRbh',retentionScore:45,funnyScore:35,payoffStrength:38,contextClarity:45,noveltyScore:38,shortsPotential:38,longFormPotential:42,transitionPotential:35,cooldownPotential:58,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:35,emotionalCategory:'emotional',reasoning:'Wholesome streamer community farewell — too insider/community-specific to land for general viewers'},
  // Batch 16
  {id:'CrunchyLovelyHamsterWow-ySgBHQqv9PcuizdI',retentionScore:45,funnyScore:50,payoffStrength:45,contextClarity:40,noveltyScore:42,shortsPotential:45,longFormPotential:42,transitionPotential:40,cooldownPotential:40,toxicityRisk:10,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:42,emotionalCategory:'other',reasoning:'Jinnytty JC clip with no transcript — can\'t assess beyond the laughing title'},
  {id:'FurryIntelligentCroissantWow-m3HtyHuOkOMCKBxM',retentionScore:60,funnyScore:58,payoffStrength:55,contextClarity:65,noveltyScore:55,shortsPotential:62,longFormPotential:52,transitionPotential:48,cooldownPotential:50,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:55,emotionalCategory:'surprise',reasoning:'Streamer reacts to friend bungee jumping saying she\'d be too scared — relatable fear that works without knowing the streamers'},
  {id:'IgnorantExuberantSpaghettiTebowing-0enOg1GuNAzLrXrD',retentionScore:40,funnyScore:42,payoffStrength:38,contextClarity:35,noveltyScore:38,shortsPotential:40,longFormPotential:38,transitionPotential:35,cooldownPotential:35,toxicityRisk:15,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:38,emotionalCategory:'surprise',reasoning:'yourragegaming JC clip with no transcript — title implies reaction content but can\'t assess quality'},
  {id:'SplendidHilariousPrariedogAsianGlow-17WxRBtgEAh8VPSI',retentionScore:30,funnyScore:28,payoffStrength:25,contextClarity:25,noveltyScore:28,shortsPotential:28,longFormPotential:20,transitionPotential:22,cooldownPotential:28,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:22,emotionalCategory:'other',reasoning:'Chinese JC clip — language barrier makes it inaccessible, should have been filtered'},
  {id:'SourSpicySquirrelPMSTwin-coixd2p8wOKmfYFM',retentionScore:78,funnyScore:82,payoffStrength:78,contextClarity:80,noveltyScore:72,shortsPotential:82,longFormPotential:70,transitionPotential:55,cooldownPotential:20,toxicityRisk:30,singingScore:0,dancingScore:0,rageScore:75,thumbnailPotential:75,emotionalCategory:'rage',reasoning:'Jinnytty goes completely nuclear about people confusing her e-bike for a scooter — sustained rage rant that\'s instantly funny'},
  {id:'PolishedBlazingPlumberJonCarnage-WhNh160Kc2O4eOWm',retentionScore:58,funnyScore:65,payoffStrength:60,contextClarity:55,noveltyScore:62,shortsPotential:65,longFormPotential:45,transitionPotential:52,cooldownPotential:42,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:48,emotionalCategory:'other',reasoning:'Dutch streamer: golden dumpling = GTA 6 this year — absurd logic that transcends language as a quick funny moment'},
  {id:'PiercingAuspiciousBobaMVGame-nu5-FVAKaLV5OzCi',retentionScore:60,funnyScore:62,payoffStrength:58,contextClarity:52,noveltyScore:55,shortsPotential:60,longFormPotential:52,transitionPotential:50,cooldownPotential:38,toxicityRisk:20,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:52,emotionalCategory:'surprise',reasoning:'Streamer gets recognized from viral clip at an event — relatable clout moment but "we\'re doing drugs" line is confusing and risky'},
  {id:'ComfortableDifficultWrenchSMOrc-THpQyrtwYeF_lJxc',retentionScore:52,funnyScore:55,payoffStrength:50,contextClarity:48,noveltyScore:52,shortsPotential:55,longFormPotential:40,transitionPotential:45,cooldownPotential:40,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:45,emotionalCategory:'surprise',reasoning:'German IRL "almost threw away the whole aura" — meme terminology is international but German limits full accessibility'},
  // Batch 17
  {id:'BloodySucculentMoonBigBrother-CKMJcEQgS8ZIpYvn',retentionScore:48,funnyScore:45,payoffStrength:42,contextClarity:45,noveltyScore:42,shortsPotential:45,longFormPotential:38,transitionPotential:38,cooldownPotential:45,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:38,emotionalCategory:'other',reasoning:'Spanish IRL asking about streamer Ibai — requires knowing who Ibai is and the Spanish boxing event'},
  {id:'WimpyOpenStarCharlietheUnicorn-kPcmJGlX36DDc5z7',retentionScore:80,funnyScore:72,payoffStrength:78,contextClarity:78,noveltyScore:72,shortsPotential:75,longFormPotential:72,transitionPotential:52,cooldownPotential:25,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:72,emotionalCategory:'surprise',reasoning:'Extended grenade discovery — "I\'m gone!" captures universal panic perfectly even without German'},
  {id:'SplendidGleamingHornetSaltBae-eAKlJCz2rJ7VggPE',retentionScore:40,funnyScore:42,payoffStrength:38,contextClarity:32,noveltyScore:38,shortsPotential:42,longFormPotential:28,transitionPotential:32,cooldownPotential:38,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:35,emotionalCategory:'cringe',reasoning:'Polish IRL clip with completely garbled transcript — can\'t assess the content'},
  {id:'AssiduousCulturedPartridgeMcaT-zyeLVsddg7OMxs6k',retentionScore:48,funnyScore:50,payoffStrength:45,contextClarity:52,noveltyScore:45,shortsPotential:52,longFormPotential:40,transitionPotential:40,cooldownPotential:52,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:45,emotionalCategory:'fail',reasoning:'Spanish IRL coaxing a dog to climb — cute animal clip but Spanish and lack of visual context limit appeal'},
  {id:'UnsightlyAltruisticOwlDuDudu-KqiR_-42OdS8-5Fx',retentionScore:30,funnyScore:28,payoffStrength:25,contextClarity:32,noveltyScore:28,shortsPotential:30,longFormPotential:20,transitionPotential:28,cooldownPotential:32,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:25,emotionalCategory:'other',reasoning:'8-second German IRL greeting clip — far too short and uneventful to include'},
  {id:'IncredulousThoughtfulGoatM4xHeh-zLCMz-hR98BauThA',retentionScore:40,funnyScore:38,payoffStrength:35,contextClarity:35,noveltyScore:40,shortsPotential:40,longFormPotential:35,transitionPotential:35,cooldownPotential:40,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:35,emotionalCategory:'other',reasoning:'German TwitchCon 2026 IRL clip with no audio — can\'t assess content without German and video'},
  {id:'EnergeticRealSpiderPJSalt-1VkYWoeFfmLLbma9',retentionScore:38,funnyScore:38,payoffStrength:38,contextClarity:40,noveltyScore:38,shortsPotential:42,longFormPotential:25,transitionPotential:38,cooldownPotential:38,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:38,emotionalCategory:'cringe',reasoning:'Very short Spanish street flirting clip — charming but too brief and unclear to work in compilation'},
  {id:'TrappedKindDinosaurItsBoshyTime-QtbzBTpr-4gZ83oC',retentionScore:40,funnyScore:42,payoffStrength:38,contextClarity:40,noveltyScore:40,shortsPotential:42,longFormPotential:30,transitionPotential:35,cooldownPotential:42,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:32,emotionalCategory:'cringe',reasoning:'German IRL toilet interruption mid-conversation — might be funny visually but requires German'},
  // Batch 18
  {id:'SavageIronicPhoneShazBotstix-nk8kpkyW57Jx3_AD',retentionScore:25,funnyScore:25,payoffStrength:20,contextClarity:22,noveltyScore:22,shortsPotential:25,longFormPotential:15,transitionPotential:22,cooldownPotential:22,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:18,emotionalCategory:'other',reasoning:'6-second German IRL clip with no transcript — essentially unassessable'},
  {id:'MoistCleanDadPunchTrees-2djFnSn9WASQFcby',retentionScore:50,funnyScore:55,payoffStrength:50,contextClarity:55,noveltyScore:48,shortsPotential:50,longFormPotential:35,transitionPotential:38,cooldownPotential:18,toxicityRisk:80,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:50,emotionalCategory:'cringe',reasoning:'Explicitly sexual IRL innuendo — far too explicit for a general compilation audience'},
  {id:'CheerfulEnthusiasticCiderKeyboardCat-dSg6SLMod_HY6aMB',retentionScore:38,funnyScore:35,payoffStrength:35,contextClarity:32,noveltyScore:35,shortsPotential:35,longFormPotential:32,transitionPotential:30,cooldownPotential:40,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:28,emotionalCategory:'fail',reasoning:'Third AUTdany German van life clip — similar workshop chaos content requiring German'},
  {id:'HeartlessEmpathicDiscBloodTrail-F5Yi6mXk0oACEOEV',retentionScore:60,funnyScore:65,payoffStrength:60,contextClarity:65,noveltyScore:62,shortsPotential:68,longFormPotential:45,transitionPotential:52,cooldownPotential:42,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:50,emotionalCategory:'cringe',reasoning:'"Feucht, feucht, feucht" — funny-sounding German word for "wet/moist" transcends the language barrier'},
  {id:'ShortImpartialButterflyBIRB-ZVGqOm5nIggZO9E_',retentionScore:68,funnyScore:72,payoffStrength:70,contextClarity:80,noveltyScore:68,shortsPotential:75,longFormPotential:55,transitionPotential:58,cooldownPotential:40,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:62,emotionalCategory:'cringe',reasoning:'"Did you just break the spaghetti?" — taps into the universal spaghetti controversy without any context needed'},
  {id:'DreamyWiseLasagnaJKanStyle-FXw10ltXeNW45tPI',retentionScore:62,funnyScore:65,payoffStrength:62,contextClarity:60,noveltyScore:60,shortsPotential:62,longFormPotential:52,transitionPotential:52,cooldownPotential:42,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:52,emotionalCategory:'cringe',reasoning:'Two Germans debating whether stranger said "thank you" or "ugly" — funny mishearing debate with minimal German needed'},
  {id:'TenuousBashfulMoonOptimizePrime-EL_NwoJK7jj-C1C0',retentionScore:65,funnyScore:60,payoffStrength:65,contextClarity:65,noveltyScore:62,shortsPotential:68,longFormPotential:55,transitionPotential:52,cooldownPotential:35,toxicityRisk:15,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:65,emotionalCategory:'fail',reasoning:'"Doro getting hit by a bike" — title promises a dramatic IRL moment, accessible without context'},
  {id:'SecretiveDullTapirResidentSleeper--rgXkFKJ0tFVd56A',retentionScore:25,funnyScore:22,payoffStrength:20,contextClarity:22,noveltyScore:20,shortsPotential:25,longFormPotential:15,transitionPotential:20,cooldownPotential:25,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:20,emotionalCategory:'other',reasoning:'Another Yxnca ":)" clip with no transcript — indistinguishable, can\'t assess'},
  // Batch 19
  {id:'ColorfulTrappedOrcaDendiFace-kUMGAqv5nfo8j7LR',retentionScore:35,funnyScore:22,payoffStrength:25,contextClarity:35,noveltyScore:28,shortsPotential:28,longFormPotential:30,transitionPotential:25,cooldownPotential:45,toxicityRisk:0,singingScore:0,dancingScore:0,rageScore:0,thumbnailPotential:25,emotionalCategory:'other',reasoning:'Spanish philosophical rant about art — inaccessible for English audience and lacks any viral hook'},
];

// Build lookup by id
const scoreMap = {};
for (const s of RAW) scoreMap[s.id] = s;

// Calculate viralityScore and ddosScore
const now = Date.now();
const scored = downloaded.map(clip => {
  const s = scoreMap[clip.id];
  if (!s) return null;

  const hoursAlive = Math.max((now - new Date(clip.created_at).getTime()) / 3600000, 0.5);
  // Without TwitchTracker avg_viewers, approximate viralityRatio with a simplified formula
  // Using views/hour vs a typical "viral" threshold of 500 views/hr
  const viewsPerHour = clip.view_count / hoursAlive;
  const viralityRatio = viewsPerHour / 500; // normalized
  const viralityScore = Math.min(100, Math.sqrt(viralityRatio) * 35);

  const tox = s.toxicityRisk > 40 ? (s.toxicityRisk - 40) * 0.5 : 0;
  const ddosScore = Math.max(0, Math.min(100,
    viralityScore    * 0.30 +
    s.retentionScore * 0.25 +
    s.funnyScore     * 0.20 +
    s.payoffStrength * 0.15 +
    s.contextClarity * 0.10 -
    tox
  ));

  const filename = clip.localPath ? require('path').basename(clip.localPath) : '';

  return {
    id: clip.id,
    clipId: clip.id,
    broadcaster_name: clip.broadcaster_name,
    title: clip.title,
    game_name: clip.game_name,
    game_id: clip.game_id,
    language: clip.language,
    duration: clip.duration,
    view_count: clip.view_count,
    created_at: clip.created_at,
    url: clip.url,
    localPath: clip.localPath,
    filename,
    preScore: clip.preScore || 0,
    viralityScore: Math.round(viralityScore * 10) / 10,
    ...s,
    ddosScore: Math.round(ddosScore * 10) / 10,
  };
}).filter(Boolean);

scored.sort((a, b) => b.ddosScore - a.ddosScore);

fs.writeFileSync(path.join(RUN_DIR,'clips','scored-clips.json'), JSON.stringify(scored, null, 2), 'utf8');

const state = JSON.parse(fs.readFileSync(path.join(RUN_DIR,'state.json'),'utf8').replace(/^﻿/,''));
state.stages.score = 'done';
state.counts.scored = scored.length;
fs.writeFileSync(path.join(RUN_DIR,'state.json'), JSON.stringify(state, null, 2), 'utf8');

console.log(`[SCORE] ${scored.length} clips scored. Top 20:`);
console.log('# | Стрімер            | Категорія        | DDOS | Funny | Shorts | Flags');
scored.slice(0, 20).forEach((c, i) => {
  const flags = [];
  if (c.toxicityRisk > 50) flags.push('TOXIC');
  if (c.singingScore > 70) flags.push('SING');
  if (c.rageScore > 60) flags.push('RAGE');
  console.log(`${String(i+1).padStart(2)} | ${c.broadcaster_name.padEnd(18)} | ${c.game_name.slice(0,16).padEnd(16)} | ${String(Math.round(c.ddosScore)).padStart(4)} | ${String(c.funnyScore).padStart(5)} | ${String(c.shortsPotential).padStart(6)} | ${flags.join(',')}`);
});
