#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const runId = process.argv[2];
if (!runId) { console.error('Usage: node save-scores.js <runId>'); process.exit(1); }

const projectDir = path.join('projects', runId);
const clipsDir = path.join(projectDir, 'clips');
const processedDir = path.join(projectDir, 'processed');

const scores = [
  { clipId: 'PreciousTiredWeaselAsianGlow--airkCp1AwBK34sW', retentionScore: 65, funnyScore: 68, payoffStrength: 65, contextClarity: 55, noveltyScore: 60, shortsPotential: 72, longFormPotential: 45, transitionPotential: 55, cooldownPotential: 30, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 15, flags: [], reasoning: 'Short IRL reaction moment with punchy title, minimal context needed' },
  { clipId: 'PlausibleVainMagpieOhMyDog-2qyhgNHQJk9nlraA', retentionScore: 68, funnyScore: 72, payoffStrength: 65, contextClarity: 78, noveltyScore: 65, shortsPotential: 65, longFormPotential: 72, transitionPotential: 60, cooldownPotential: 65, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 0, flags: [], reasoning: 'Wholesome rule-abiding fisherman keeps exactly one fish — universally relatable and charming' },
  { clipId: 'PlayfulLaconicDotterelDancingBaby-JuZ492Y64_oZLBZJ', retentionScore: 42, funnyScore: 45, payoffStrength: 42, contextClarity: 40, noveltyScore: 40, shortsPotential: 42, longFormPotential: 32, transitionPotential: 38, cooldownPotential: 38, musicRisk: 0, toxicityRisk: 12, singingScore: 0, dancingScore: 0, rageScore: 0, flags: [], reasoning: 'Title implies something happened but transcript reveals almost no context' },
  { clipId: 'InterestingAggressiveWaspShadyLulu-MKVk1WKm1MnGYqO0', retentionScore: 68, funnyScore: 55, payoffStrength: 72, contextClarity: 62, noveltyScore: 55, shortsPotential: 68, longFormPotential: 65, transitionPotential: 55, cooldownPotential: 30, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 20, flags: [], reasoning: 'Commentated 1v1 Valorant clutch with energetic caster reaction' },
  { clipId: 'PopularOutstandingPastaTTours-y74m5fNhfCOBGRpZ', retentionScore: 48, funnyScore: 45, payoffStrength: 52, contextClarity: 42, noveltyScore: 48, shortsPotential: 45, longFormPotential: 48, transitionPotential: 40, cooldownPotential: 35, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 10, flags: [], reasoning: 'Gameplay clip with minimal commentary, lacks strong payoff' },
  { clipId: 'LongRamshackleBeanJKanStyle-3Des94HRrC4cq1a7', retentionScore: 75, funnyScore: 78, payoffStrength: 72, contextClarity: 65, noveltyScore: 68, shortsPotential: 72, longFormPotential: 68, transitionPotential: 60, cooldownPotential: 30, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 55, flags: [], reasoning: 'Pro player ame immediately calls GG and tilts out — the reaction and repeated "he called gg" is gold' },
  { clipId: 'IgnorantGlutenFreeHerdRlyTho-6fOePkqeg0W1AiTB', retentionScore: 50, funnyScore: 52, payoffStrength: 55, contextClarity: 38, noveltyScore: 50, shortsPotential: 48, longFormPotential: 45, transitionPotential: 42, cooldownPotential: 35, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 20, flags: [], reasoning: 'Thai Valorant clip with no English context for international audience' },
  { clipId: 'ResoluteConfidentCockroachBrokeBack-wQnDPxV6MF1S7442', retentionScore: 62, funnyScore: 65, payoffStrength: 65, contextClarity: 75, noveltyScore: 62, shortsPotential: 72, longFormPotential: 55, transitionPotential: 55, cooldownPotential: 78, musicRisk: 75, toxicityRisk: 0, singingScore: 85, dancingScore: 70, rageScore: 0, flags: ['CHILL_FINALE', 'MUSIC_RISK_ABBA'], reasoning: 'Lyasyaa singing ABBA Dancing Queen — high music risk but perfect chill finale candidate' },
  { clipId: 'DrabSaltyOwlBigBrother-dDbFed6ywzo-XCxa', retentionScore: 65, funnyScore: 68, payoffStrength: 68, contextClarity: 72, noveltyScore: 62, shortsPotential: 72, longFormPotential: 58, transitionPotential: 62, cooldownPotential: 45, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 0, flags: [], reasoning: 'Beer rant leading into unexpected explosive sneeze — clear setup and payoff' },
  { clipId: 'LuckyGoldenVelociraptorCmonBruh-bWTptMPnMbs0iid2', retentionScore: 68, funnyScore: 72, payoffStrength: 68, contextClarity: 55, noveltyScore: 65, shortsPotential: 62, longFormPotential: 65, transitionPotential: 60, cooldownPotential: 35, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 10, flags: ['DUPLICATE_INCIDENT_ZARBEX'], reasoning: 'Pigeon KO at gas station, higher views version — funny nature moment universally understood' },
  { clipId: 'ObservantFurtiveTruffleItsBoshyTime-h41rocXR9NI3DzsX', retentionScore: 62, funnyScore: 68, payoffStrength: 62, contextClarity: 50, noveltyScore: 60, shortsPotential: 78, longFormPotential: 48, transitionPotential: 65, cooldownPotential: 50, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 0, flags: [], reasoning: 'stylishnoob4 high-view clip with signature humor style, short and punchy' },
  { clipId: 'CuteVastHawkTheTarFu-DzvmkIVgPLImvDnk', retentionScore: 65, funnyScore: 70, payoffStrength: 65, contextClarity: 65, noveltyScore: 65, shortsPotential: 75, longFormPotential: 55, transitionPotential: 65, cooldownPotential: 55, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 0, flags: [], reasoning: 'Confusion about mysterious green-suited person in bathroom — relatable absurd moment' },
  { clipId: 'EndearingOilyHerbsItsBoshyTime-BZhwWLwDioF1esvD', retentionScore: 68, funnyScore: 60, payoffStrength: 75, contextClarity: 60, noveltyScore: 62, shortsPotential: 72, longFormPotential: 60, transitionPotential: 62, cooldownPotential: 35, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 25, flags: [], reasoning: 'Caster going wild over Hypex impossible clutch with bomb in water' },
  { clipId: 'BlushingBraveJackalOSfrog-lCCzIcudAvw2fzsF', retentionScore: 52, funnyScore: 55, payoffStrength: 50, contextClarity: 52, noveltyScore: 48, shortsPotential: 52, longFormPotential: 45, transitionPotential: 45, cooldownPotential: 40, musicRisk: 15, toxicityRisk: 5, singingScore: 0, dancingScore: 0, rageScore: 30, flags: [], reasoning: 'Drake auto-tune rant has energy but limited international appeal' },
  { clipId: 'LivelyFancyBorkFloof-7_-kxAGzpOC3Knfi', retentionScore: 45, funnyScore: 42, payoffStrength: 48, contextClarity: 42, noveltyScore: 42, shortsPotential: 40, longFormPotential: 45, transitionPotential: 38, cooldownPotential: 35, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 0, flags: [], reasoning: 'Esports casting clip requires insider knowledge of Caedrel to land' },
  { clipId: 'PlumpFuriousWitchTF2John-DS5MA-c62pFBnsrt', retentionScore: 62, funnyScore: 65, payoffStrength: 62, contextClarity: 62, noveltyScore: 58, shortsPotential: 62, longFormPotential: 55, transitionPotential: 55, cooldownPotential: 45, musicRisk: 0, toxicityRisk: 5, singingScore: 0, dancingScore: 0, rageScore: 0, flags: [], reasoning: 'Bizarre finger-as-spare-ribs monologue is weird enough to be memorable' },
  { clipId: 'BrightMoldyKaleArgieB8-f5AH46OxxPhusrBa', retentionScore: 72, funnyScore: 65, payoffStrength: 75, contextClarity: 60, noveltyScore: 65, shortsPotential: 72, longFormPotential: 68, transitionPotential: 65, cooldownPotential: 25, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 35, flags: [], reasoning: 'French caster absolutely losing it over KSCERATO 1v3 clutch — energy is contagious' },
  { clipId: 'VastDepressedVelociraptorVoHiYo-2I0T9AeVoVTxI1Wd', retentionScore: 50, funnyScore: 55, payoffStrength: 52, contextClarity: 40, noveltyScore: 48, shortsPotential: 50, longFormPotential: 45, transitionPotential: 42, cooldownPotential: 55, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 15, flags: [], reasoning: 'Japanese towel debate clip requires cultural context to fully appreciate' },
  { clipId: 'CovertSpineyKleeNinjaGrumpy-Ulv-ad9s4tC8lf3V', retentionScore: 48, funnyScore: 45, payoffStrength: 48, contextClarity: 35, noveltyScore: 45, shortsPotential: 45, longFormPotential: 42, transitionPotential: 40, cooldownPotential: 55, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 0, flags: [], reasoning: 'Chinese IRL relationship monologue, beautiful delivery but low international clarity' },
  { clipId: 'PunchyHyperWebAllenHuhu-ujCtLippMQmWU54c', retentionScore: 72, funnyScore: 75, payoffStrength: 70, contextClarity: 68, noveltyScore: 65, shortsPotential: 78, longFormPotential: 60, transitionPotential: 68, cooldownPotential: 42, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 15, flags: [], reasoning: 'HAchubby struggling vs mattress with panic escalation — title alone sells the bit' },
  { clipId: 'TrappedPlausibleCrowGingerPower-g8zEaZqG3nh1UdOT', retentionScore: 65, funnyScore: 62, payoffStrength: 68, contextClarity: 72, noveltyScore: 60, shortsPotential: 72, longFormPotential: 52, transitionPotential: 68, cooldownPotential: 25, musicRisk: 0, toxicityRisk: 8, singingScore: 0, dancingScore: 0, rageScore: 10, flags: [], reasoning: 'FORTY SUBS explosion — raw unfiltered joy at small milestone is universally wholesome' },
  { clipId: 'TastyPowerfulPlumagePastaThat-xq1jLoGUDIGVxdCj', retentionScore: 35, funnyScore: 32, payoffStrength: 25, contextClarity: 55, noveltyScore: 28, shortsPotential: 28, longFormPotential: 35, transitionPotential: 38, cooldownPotential: 62, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 0, flags: [], reasoning: 'Stream schedule announcement clip, no entertainment value' },
  { clipId: 'CrypticCrepuscularSnailBIRB-W6QHyQChLCah0Mbz', retentionScore: 60, funnyScore: 65, payoffStrength: 60, contextClarity: 48, noveltyScore: 55, shortsPotential: 72, longFormPotential: 45, transitionPotential: 62, cooldownPotential: 48, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 0, flags: [], reasoning: 'stylishnoob4 clip about full names, solid humor but requires Japanese context' },
  { clipId: 'KnottyCarefulTrayMau5-gvYbjsM5nA31I-g2', retentionScore: 65, funnyScore: 55, payoffStrength: 70, contextClarity: 65, noveltyScore: 60, shortsPotential: 65, longFormPotential: 62, transitionPotential: 55, cooldownPotential: 28, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 10, flags: [], reasoning: 'Primmie ace after rez beautifully called by commentator — clean esports moment' },
  { clipId: 'CarefulAmazonianMilkItsBoshyTime-5HwBRNbV2whtnm__', retentionScore: 52, funnyScore: 60, payoffStrength: 58, contextClarity: 40, noveltyScore: 52, shortsPotential: 55, longFormPotential: 48, transitionPotential: 48, cooldownPotential: 38, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 5, flags: [], reasoning: 'Chinese streamer pulling something lower and lower, funny escalation but needs subtitle context' },
  { clipId: 'BraveTubularJalapenoPMSTwin-JgygAU0jtUbN__on', retentionScore: 35, funnyScore: 38, payoffStrength: 32, contextClarity: 25, noveltyScore: 35, shortsPotential: 30, longFormPotential: 28, transitionPotential: 30, cooldownPotential: 40, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 0, flags: [], reasoning: 'Repeated word clip with no discernible payoff or context' },
  { clipId: 'MoralGorgeousJuiceFeelsBadMan-jjjE7UWnsfjH_7LA', retentionScore: 65, funnyScore: 70, payoffStrength: 65, contextClarity: 52, noveltyScore: 60, shortsPotential: 60, longFormPotential: 62, transitionPotential: 55, cooldownPotential: 35, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 10, flags: ['DUPLICATE_INCIDENT_MONTANABLACK'], reasoning: 'Same pigeon gas station incident from zarbex POV — MontanaBlack88 version preferred (2x views)' },
  { clipId: 'AstuteLightManateeKreygasm-Y9o2_knZ5DecbGI4', retentionScore: 62, funnyScore: 55, payoffStrength: 58, contextClarity: 62, noveltyScore: 55, shortsPotential: 55, longFormPotential: 62, transitionPotential: 55, cooldownPotential: 68, musicRisk: 30, toxicityRisk: 0, singingScore: 35, dancingScore: 0, rageScore: 0, flags: [], reasoning: 'Clair Obscur singer appreciated by streamer, chill watching vibe' },
  { clipId: 'BlindingStupidEelCeilingCat-mpu7hSIfNde7W2X2', retentionScore: 35, funnyScore: 38, payoffStrength: 40, contextClarity: 28, noveltyScore: 35, shortsPotential: 35, longFormPotential: 30, transitionPotential: 32, cooldownPotential: 35, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 35, flags: [], reasoning: 'Arabic clip with 21 views, no international appeal' },
  { clipId: 'TrustworthyVibrantPiePhilosoraptor-RHx24Roql-VmMQV2', retentionScore: 32, funnyScore: 30, payoffStrength: 35, contextClarity: 28, noveltyScore: 32, shortsPotential: 35, longFormPotential: 28, transitionPotential: 32, cooldownPotential: 35, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 10, flags: [], reasoning: 'Korean Fortnite clip with empty transcript and only 51 views' },
  { clipId: 'AstuteTawdryMacaroniDendiFace-6IlIAX0CzPQZe2iH', retentionScore: 45, funnyScore: 48, payoffStrength: 52, contextClarity: 35, noveltyScore: 42, shortsPotential: 45, longFormPotential: 42, transitionPotential: 40, cooldownPotential: 38, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 20, flags: [], reasoning: 'Chinese LoL gameplay moment, unclear without subtitles' },
  { clipId: 'ObliviousAbstruseCasetteRaccAttack-XnTruI5WNM-JZDCY', retentionScore: 62, funnyScore: 68, payoffStrength: 65, contextClarity: 55, noveltyScore: 60, shortsPotential: 72, longFormPotential: 38, transitionPotential: 70, cooldownPotential: 30, musicRisk: 0, toxicityRisk: 8, singingScore: 0, dancingScore: 0, rageScore: 15, flags: [], reasoning: 'Only 8.5s of pure chaos — doink-a-guagua is wonderfully unhinged and transition-friendly' },
  { clipId: 'WonderfulLongStinkbugDuDudu-uwkirwLqkRhDe9D7', retentionScore: 55, funnyScore: 62, payoffStrength: 58, contextClarity: 50, noveltyScore: 52, shortsPotential: 60, longFormPotential: 48, transitionPotential: 58, cooldownPotential: 40, musicRisk: 20, toxicityRisk: 0, singingScore: 0, dancingScore: 30, rageScore: 0, flags: [], reasoning: 'French streamer dabs to carousel music at ZLAN event — visual gag that transcends language' },
  { clipId: 'TenderTsundereLaptopLeeroyJenkins-uH5haueaVS5DPzsM', retentionScore: 62, funnyScore: 65, payoffStrength: 68, contextClarity: 72, noveltyScore: 58, shortsPotential: 62, longFormPotential: 58, transitionPotential: 60, cooldownPotential: 38, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 35, flags: [], reasoning: 'Subnautica 2 shockwave death with clear English transcript and great "conditions incompatible with life" line' },
  { clipId: 'GiftedExcitedPrariedogRuleFive-W45zkEB4ukOQFwm0', retentionScore: 40, funnyScore: 45, payoffStrength: 42, contextClarity: 32, noveltyScore: 40, shortsPotential: 38, longFormPotential: 42, transitionPotential: 35, cooldownPotential: 48, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 10, flags: [], reasoning: 'Long Minecraft JP clip with only 95 views, no clear hook' },
  { clipId: 'DeadSplendidAniseSeemsGood--7bNn2qTweTC7qDM', retentionScore: 60, funnyScore: 65, payoffStrength: 62, contextClarity: 68, noveltyScore: 58, shortsPotential: 65, longFormPotential: 55, transitionPotential: 62, cooldownPotential: 45, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 10, flags: [], reasoning: 'JERICHO calling catastrophic Forza crash "a little scratch" — understated delivery is funny' },
  { clipId: 'SquareGiantKiwiBIRB-sq_VKQW_0sVdNNp-', retentionScore: 50, funnyScore: 55, payoffStrength: 60, contextClarity: 42, noveltyScore: 48, shortsPotential: 55, longFormPotential: 45, transitionPotential: 52, cooldownPotential: 40, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 15, flags: [], reasoning: 'Japanese Overwatch exclamation compilation, decent energy but low clarity' },
  { clipId: 'ObliqueEnthusiasticChowderWutFace-8JjNLKhl-SbjyuBL', retentionScore: 55, funnyScore: 60, payoffStrength: 55, contextClarity: 40, noveltyScore: 52, shortsPotential: 50, longFormPotential: 55, transitionPotential: 45, cooldownPotential: 55, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 5, flags: [], reasoning: 'stylishnoob4 story about world line changing — narrative clip needing Japanese' },
  { clipId: 'TemperedGoldenSlothDerp-ppP7UWJU6-bJ5E-h', retentionScore: 40, funnyScore: 42, payoffStrength: 45, contextClarity: 38, noveltyScore: 38, shortsPotential: 40, longFormPotential: 35, transitionPotential: 38, cooldownPotential: 35, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 20, flags: [], reasoning: 'Dota 2 clip with 33 views and no clear comedic or impressive moment' },
  { clipId: 'TalentedPuzzledWoodpeckerBibleThump-6XfRUWPsdjLnLtdV', retentionScore: 52, funnyScore: 58, payoffStrength: 50, contextClarity: 48, noveltyScore: 48, shortsPotential: 50, longFormPotential: 50, transitionPotential: 45, cooldownPotential: 48, musicRisk: 0, toxicityRisk: 15, singingScore: 0, dancingScore: 0, rageScore: 25, flags: [], reasoning: 'Spanish LoL rant about AI calling people names is somewhat relatable but niche' },
  { clipId: 'DifficultHelplessDootKappaWealth-J51sclAGLjEevgfE', retentionScore: 55, funnyScore: 62, payoffStrength: 58, contextClarity: 50, noveltyScore: 52, shortsPotential: 60, longFormPotential: 48, transitionPotential: 55, cooldownPotential: 38, musicRisk: 0, toxicityRisk: 10, singingScore: 0, dancingScore: 0, rageScore: 45, flags: [], reasoning: 'French Overwatch rage clip with "ce poulet" — works visually even without French' },
  { clipId: 'HungryStylishJamDAESuppy-NvzY42x3cuJM7Kkq', retentionScore: 48, funnyScore: 52, payoffStrength: 52, contextClarity: 40, noveltyScore: 45, shortsPotential: 48, longFormPotential: 45, transitionPotential: 42, cooldownPotential: 42, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 10, flags: [], reasoning: 'Japanese Valorant clip about touching glass with fingers, limited international appeal' },
  { clipId: 'ArtsyTangentialToadFunRun-5uF6xBCIGg-ylrIK', retentionScore: 42, funnyScore: 45, payoffStrength: 42, contextClarity: 38, noveltyScore: 40, shortsPotential: 45, longFormPotential: 28, transitionPotential: 42, cooldownPotential: 35, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 10, flags: [], reasoning: 'Very short Portuguese Valorant clip, almost no context' },
  { clipId: 'TsundereSmokyVanillaWutFace-LGTJk6k9DVvebksF', retentionScore: 40, funnyScore: 42, payoffStrength: 40, contextClarity: 30, noveltyScore: 38, shortsPotential: 38, longFormPotential: 35, transitionPotential: 35, cooldownPotential: 40, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 20, flags: ['EMPTY_TRANSCRIPT'], reasoning: 'Subnautica 2 clip with failed transcription, cannot assess content' },
  { clipId: 'DeterminedEsteemedDunlinSmoocherZ-HGP2cf8QJL-g_9VO', retentionScore: 52, funnyScore: 62, payoffStrength: 58, contextClarity: 38, noveltyScore: 50, shortsPotential: 52, longFormPotential: 50, transitionPotential: 45, cooldownPotential: 50, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 10, flags: [], reasoning: 'Japanese GTA V clip about holding in laughter, has charm but needs context' },
  { clipId: 'ShyPreciousVanillaPMSTwin-2xeleUD54g5To4DX', retentionScore: 35, funnyScore: 38, payoffStrength: 35, contextClarity: 28, noveltyScore: 35, shortsPotential: 35, longFormPotential: 28, transitionPotential: 32, cooldownPotential: 40, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 0, flags: [], reasoning: 'Norwegian/Minecraft clip with single odd phrase as transcript, no clear value' },
  { clipId: 'DarlingAlivePheasantThisIsSparta-Be2FnzoOWIFC2U2d', retentionScore: 25, funnyScore: 25, payoffStrength: 20, contextClarity: 22, noveltyScore: 25, shortsPotential: 20, longFormPotential: 18, transitionPotential: 22, cooldownPotential: 28, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 0, flags: [], reasoning: 'Transcript is only subtitle credits, 8 views, no content' },
  { clipId: 'ToughDepressedFishKappaPride-Vvr0iQfb8hHYpAbg', retentionScore: 55, funnyScore: 48, payoffStrength: 60, contextClarity: 55, noveltyScore: 50, shortsPotential: 58, longFormPotential: 50, transitionPotential: 52, cooldownPotential: 32, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 20, flags: [], reasoning: 'Apex Legends frantic squad comms, decent energy but generic' },
  { clipId: 'RockyMoralPeafowlImGlitch-GPoLkYET3kdXngme', retentionScore: 48, funnyScore: 52, payoffStrength: 48, contextClarity: 42, noveltyScore: 48, shortsPotential: 48, longFormPotential: 42, transitionPotential: 45, cooldownPotential: 45, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 10, flags: [], reasoning: 'French ZLAN clip about game rules, needs context to fully appreciate' },
  { clipId: 'ArtsyGiantMarjoramSoBayed-2hI67PxGfNMlupvI', retentionScore: 52, funnyScore: 55, payoffStrength: 50, contextClarity: 52, noveltyScore: 48, shortsPotential: 55, longFormPotential: 48, transitionPotential: 50, cooldownPotential: 45, musicRisk: 25, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 10, flags: [], reasoning: 'Im_Dontai Marvel Rivals clip — mentions playing music (risk) but casual and relatable' },
  { clipId: 'MildGrotesqueWeaselPlanking-eHv3q8JJODoDW-gG', retentionScore: 50, funnyScore: 52, payoffStrength: 48, contextClarity: 52, noveltyScore: 45, shortsPotential: 48, longFormPotential: 48, transitionPotential: 45, cooldownPotential: 40, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 25, flags: [], reasoning: '"Too many targets" Marvel Rivals reaction — decent but too generic' },
  { clipId: 'WimpyFragileRadicchioPartyTime-O98eANB_rrQzlPdi', retentionScore: 62, funnyScore: 65, payoffStrength: 68, contextClarity: 58, noveltyScore: 58, shortsPotential: 68, longFormPotential: 50, transitionPotential: 62, cooldownPotential: 28, musicRisk: 0, toxicityRisk: 8, singingScore: 0, dancingScore: 0, rageScore: 30, flags: [], reasoning: 'Overwatch slam combo triggers genuine "oh my god" panic reaction — short and punchy' },
  { clipId: 'MotionlessAgreeableRamenTTours-R-VuPdtLOwLvAQMi', retentionScore: 65, funnyScore: 65, payoffStrength: 68, contextClarity: 65, noveltyScore: 60, shortsPotential: 62, longFormPotential: 62, transitionPotential: 58, cooldownPotential: 55, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 0, flags: [], reasoning: 'Girlfriend moving in announcement mid-stream — "Colidays" stumble then real news lands well' },
  { clipId: 'FurtiveSmoothTrianglePeoplesChamp-02-j6GiCyj5mSW6v', retentionScore: 68, funnyScore: 72, payoffStrength: 68, contextClarity: 62, noveltyScore: 65, shortsPotential: 72, longFormPotential: 60, transitionPotential: 65, cooldownPotential: 40, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 10, flags: [], reasoning: 'Rubius surprised by Shinkansen in Forza — "me cago en mi puta vida" reaction is visceral and funny' },
  { clipId: 'SmokyMushyGrasshopperWow-Rj1z5G4AAwILiJUw', retentionScore: 50, funnyScore: 52, payoffStrength: 52, contextClarity: 38, noveltyScore: 48, shortsPotential: 50, longFormPotential: 45, transitionPotential: 48, cooldownPotential: 40, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 10, flags: [], reasoning: 'Chinese Forza clip, limited context' },
  { clipId: 'SecretiveCorrectEelPRChase-NN8kdCuoVH08u4x8', retentionScore: 52, funnyScore: 58, payoffStrength: 55, contextClarity: 38, noveltyScore: 50, shortsPotential: 50, longFormPotential: 55, transitionPotential: 45, cooldownPotential: 52, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 10, flags: [], reasoning: 'Japanese GTA V story clip, requires Japanese comprehension' },
  { clipId: 'FlirtyPopularRabbitPastaThat-MhPfzeP1BT-jnnop', retentionScore: 5, funnyScore: 5, payoffStrength: 5, contextClarity: 5, noveltyScore: 5, shortsPotential: 5, longFormPotential: 5, transitionPotential: 5, cooldownPotential: 5, musicRisk: 0, toxicityRisk: 100, singingScore: 0, dancingScore: 0, rageScore: 0, flags: ['RUSSIAN_CONTENT', 'EXCLUDE'], reasoning: 'Russian language content — must exclude per channel policy' },
  { clipId: 'PluckyEnchantingScallionRlyTho-9XLfuLltArDMaXnW', retentionScore: 58, funnyScore: 62, payoffStrength: 58, contextClarity: 42, noveltyScore: 52, shortsPotential: 58, longFormPotential: 50, transitionPotential: 52, cooldownPotential: 50, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 0, flags: [], reasoning: 'stylishnoob4 fan encounter story — charming but needs Japanese for full effect' },
  { clipId: 'ZanyWiseBoarJonCarnage-eRIChUqU4GWINCjy', retentionScore: 50, funnyScore: 55, payoffStrength: 50, contextClarity: 35, noveltyScore: 48, shortsPotential: 48, longFormPotential: 48, transitionPotential: 42, cooldownPotential: 52, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 0, flags: [], reasoning: 'Japanese coin trend discussion, low clarity for non-Japanese audience' },
  { clipId: 'RoughSlickTubersCharlietheUnicorn-kj7aX_8mFCBvaKav', retentionScore: 60, funnyScore: 65, payoffStrength: 62, contextClarity: 68, noveltyScore: 58, shortsPotential: 65, longFormPotential: 52, transitionPotential: 60, cooldownPotential: 42, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 0, flags: [], reasoning: 'Painful hiccup mid-sentence — relatable physical comedy moment' },
  { clipId: 'SilkyOptimisticMetalAliens-BEgupFgWqyrjOgXT', retentionScore: 52, funnyScore: 55, payoffStrength: 55, contextClarity: 38, noveltyScore: 52, shortsPotential: 55, longFormPotential: 50, transitionPotential: 45, cooldownPotential: 60, musicRisk: 40, toxicityRisk: 0, singingScore: 55, dancingScore: 0, rageScore: 0, flags: [], reasoning: 'Chinese IRL singing clip, good energy but music copyright risk' },
  { clipId: 'DaintyMoralKumquatSoonerLater-5_WeuzeAUAlQiy_6', retentionScore: 52, funnyScore: 55, payoffStrength: 52, contextClarity: 40, noveltyScore: 48, shortsPotential: 52, longFormPotential: 48, transitionPotential: 45, cooldownPotential: 52, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 0, flags: [], reasoning: 'stylishnoob4 medication story, requires Japanese fluency' },
  { clipId: 'HonestBrightKeyboardKeepo-vzyl3V9bPciC8O28', retentionScore: 35, funnyScore: 40, payoffStrength: 38, contextClarity: 42, noveltyScore: 35, shortsPotential: 35, longFormPotential: 25, transitionPotential: 30, cooldownPotential: 28, musicRisk: 0, toxicityRisk: 60, singingScore: 0, dancingScore: 0, rageScore: 15, flags: ['TOXIC_SEXUAL'], reasoning: 'Sexual Spanish bait clip, clearly inappropriate for family-friendly channel' },
  { clipId: 'TransparentHonorableOrangeNotLikeThis-zdRYa3dCgfCUpdW4', retentionScore: 50, funnyScore: 58, payoffStrength: 50, contextClarity: 38, noveltyScore: 48, shortsPotential: 48, longFormPotential: 50, transitionPotential: 42, cooldownPotential: 55, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 0, flags: [], reasoning: 'Japanese routine talk, no strong hook for non-Japanese viewers' },
  { clipId: 'PeacefulArbitraryLEDTinyFace-gBPO45sDsKnn74C0', retentionScore: 48, funnyScore: 52, payoffStrength: 50, contextClarity: 42, noveltyScore: 45, shortsPotential: 52, longFormPotential: 38, transitionPotential: 48, cooldownPotential: 32, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 25, flags: [], reasoning: 'Polish Brawl Stars hype clip — energetic but niche audience' },
  { clipId: 'BlueFrigidAlmondCmonBruh-dUwsT4brCYu9wzG7', retentionScore: 52, funnyScore: 58, payoffStrength: 52, contextClarity: 40, noveltyScore: 50, shortsPotential: 55, longFormPotential: 48, transitionPotential: 48, cooldownPotential: 52, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 0, flags: [], reasoning: 'stylishnoob4 weight loss bench story — interesting but needs Japanese' },
  { clipId: 'VictoriousRepleteCocoaGivePLZ-TSUoruulseTOTVyM', retentionScore: 52, funnyScore: 55, payoffStrength: 52, contextClarity: 48, noveltyScore: 48, shortsPotential: 55, longFormPotential: 42, transitionPotential: 52, cooldownPotential: 32, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 20, flags: [], reasoning: 'German Brawl Stars hype clip, short and energetic' },
  { clipId: 'IronicHeartlessGoldfishHoneyBadger-umcJm1TPeRmcC3BL', retentionScore: 48, funnyScore: 55, payoffStrength: 55, contextClarity: 52, noveltyScore: 48, shortsPotential: 55, longFormPotential: 42, transitionPotential: 50, cooldownPotential: 35, musicRisk: 0, toxicityRisk: 20, singingScore: 0, dancingScore: 0, rageScore: 10, flags: [], reasoning: 'Spanish bait clip getting banned — slight toxicity risk but kind of funny' },
  { clipId: 'OriginalPlumpPandaGingerPower-6VEir0iVHq9bjHkY', retentionScore: 50, funnyScore: 55, payoffStrength: 52, contextClarity: 42, noveltyScore: 48, shortsPotential: 52, longFormPotential: 45, transitionPotential: 48, cooldownPotential: 38, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 10, flags: ['EMPTY_TRANSCRIPT'], reasoning: 'Peereira7 Valorant clip with failed transcription and title suggests kiss/reaction' },
  { clipId: 'SweetWimpyAmazonSwiftRage-K9lufVK94oLviiL6', retentionScore: 72, funnyScore: 65, payoffStrength: 70, contextClarity: 62, noveltyScore: 68, shortsPotential: 72, longFormPotential: 68, transitionPotential: 58, cooldownPotential: 42, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 0, flags: [], reasoning: 'German streamer hyping friend Caro doing ice bath — genuine wholesome energy and suspense' },
  { clipId: 'AnimatedVainTrollWow-2FjmoooF-yLXrjvr', retentionScore: 62, funnyScore: 68, payoffStrength: 65, contextClarity: 52, noveltyScore: 62, shortsPotential: 62, longFormPotential: 58, transitionPotential: 58, cooldownPotential: 40, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 10, flags: [], reasoning: 'ZLAN intruder disguised and got past security — "il est déguisé" reveal is a solid moment' },
  { clipId: 'SingleDeliciousWaffleRalpherZ-etO_c8whPMcj4aIa', retentionScore: 55, funnyScore: 60, payoffStrength: 58, contextClarity: 52, noveltyScore: 52, shortsPotential: 58, longFormPotential: 52, transitionPotential: 55, cooldownPotential: 35, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 30, flags: [], reasoning: 'CrazyMonti celebrating 4K concurrent viewers while owning stream snipers' },
  { clipId: 'CourageousPerfectDotterelMoreCowbell-61t-mPViBTAZVOCN', retentionScore: 62, funnyScore: 68, payoffStrength: 65, contextClarity: 50, noveltyScore: 60, shortsPotential: 68, longFormPotential: 60, transitionPotential: 55, cooldownPotential: 45, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 25, flags: [], reasoning: 'Japanese Apex streamer commentary on fighting a pro, self-deprecating humor lands well' },
  { clipId: 'InspiringCoyLampPeoplesChamp-oMPVtbmKFJ8FHKTt', retentionScore: 62, funnyScore: 52, payoffStrength: 68, contextClarity: 62, noveltyScore: 58, shortsPotential: 65, longFormPotential: 58, transitionPotential: 55, cooldownPotential: 28, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 10, flags: [], reasoning: 'Primmie 4K with clean caster call, strong play-by-play' },
  { clipId: 'ProductiveArtisticBaconArgieB8-c4XGkNfkVsSmlQh6', retentionScore: 65, funnyScore: 68, payoffStrength: 65, contextClarity: 55, noveltyScore: 62, shortsPotential: 80, longFormPotential: 50, transitionPotential: 68, cooldownPotential: 65, musicRisk: 0, toxicityRisk: 0, singingScore: 45, dancingScore: 60, rageScore: 0, flags: [], reasoning: 'VTuber 狐白うる cute celebration reaction — pure joy, very high shorts potential' },
  { clipId: 'SlipperyBlatantCaribouCoolStoryBro-TdY2zWM4D89FjTBn', retentionScore: 70, funnyScore: 72, payoffStrength: 68, contextClarity: 52, noveltyScore: 68, shortsPotential: 78, longFormPotential: 62, transitionPotential: 62, cooldownPotential: 42, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 30, flags: [], reasoning: 'miaknightley 反省会 — using being a woman as excuse, delivered with perfect self-aware timing' },
  { clipId: 'SmilingResilientWoodcockPRChase-ThZ9njpNj9dDEydC', retentionScore: 68, funnyScore: 72, payoffStrength: 68, contextClarity: 50, noveltyScore: 65, shortsPotential: 68, longFormPotential: 65, transitionPotential: 60, cooldownPotential: 50, musicRisk: 0, toxicityRisk: 0, singingScore: 0, dancingScore: 0, rageScore: 10, flags: [], reasoning: 'Store goes silent when Shanks name is mentioned — comedic concept resonates even without Japanese' }
];

function calcDdosScore(s) {
  return Math.round(
    s.retentionScore  * 0.30 +
    s.funnyScore      * 0.25 +
    s.payoffStrength  * 0.20 +
    s.contextClarity  * 0.15 +
    s.noveltyScore    * 0.10 -
    (s.musicRisk > 60   ? (s.musicRisk   - 60) * 0.3 : 0) -
    (s.toxicityRisk > 40 ? (s.toxicityRisk - 40) * 0.5 : 0)
  );
}

const clips = JSON.parse(fs.readFileSync(path.join(clipsDir, 'downloaded-clips.json'), 'utf8'));
const allScores = [];

for (const score of scores) {
  score.ddosScore = calcDdosScore(score);
  const clip = clips.find(c => c.id === score.clipId);
  if (!clip) { console.warn('Clip not found:', score.clipId); continue; }
  const scoreWithMeta = {
    ...score,
    broadcaster_name: clip.broadcaster_name,
    game_name: clip.game_name,
    duration: clip.duration,
    title: clip.title,
    localPath: clip.localPath
  };
  const scoreDir = path.join(processedDir, score.clipId);
  fs.mkdirSync(scoreDir, { recursive: true });
  fs.writeFileSync(path.join(scoreDir, 'score.json'), JSON.stringify(scoreWithMeta, null, 2));
  allScores.push(scoreWithMeta);
}

allScores.sort((a, b) => b.ddosScore - a.ddosScore);

const scoredClips = clips.map(clip => {
  const score = allScores.find(s => s.clipId === clip.id) || {};
  return { ...clip, ...score };
}).sort((a, b) => (b.ddosScore || 0) - (a.ddosScore || 0));

fs.writeFileSync(path.join(clipsDir, 'scored-clips.json'), JSON.stringify(scoredClips, null, 2));

const statePath = path.join(projectDir, 'state.json');
const state = JSON.parse(fs.readFileSync(statePath, 'utf8'));
state.stages.score = 'done';
state.counts.scored = scoredClips.length;
fs.writeFileSync(statePath, JSON.stringify(state, null, 2));

console.log('\n=== TOP 20 CLIPS ===');
console.log('Rk | Streamer              | Category          | DDOS | Funny | Shorts | Rage | Sing | Flags');
console.log('---|----------------------|-------------------|------|-------|--------|------|------|------');
scoredClips.slice(0, 20).forEach((c, i) => {
  const streamer = (c.broadcaster_name || '').padEnd(20).slice(0, 20);
  const cat = (c.game_name || '').padEnd(17).slice(0, 17);
  const flags = (c.flags || []).join(',');
  console.log(`${String(i+1).padStart(2)} | ${streamer} | ${cat} | ${String(c.ddosScore||0).padStart(4)} | ${String(c.funnyScore||0).padStart(5)} | ${String(c.shortsPotential||0).padStart(6)} | ${String(c.rageScore||0).padStart(4)} | ${String(c.singingScore||0).padStart(4)} | ${flags}`);
});
console.log(`\nScored ${scoredClips.length} clips.`);
